### PR TITLE
Export calendar as ics, with built in notification subscription handler

### PR DESCRIPTION
**Pull request by thefudgeishot**
### **Description**
These changes add the ability to export the gibbon calendar to an ics file, this can be done by the calendar owner and those who wish to export the file for them(Event notifications and prefixes are supported). In case of any updates from the timetable, timetable admins will be able to post a notification to all those who have downloaded the calendar informing them of the update and how to download the new timetable.

### **Motivation and Context**
This feature will allow students and staff to check their timetable without needing to log into gibbon. This also allows the events to come in as push notifications from the calendar app they choose to import it into.

### **How Has This Been Tested?**
This has been tested on my machine(Manjaro GNU/Linux Pacman XAMPP Apache with 7.4.27) as well as @powertashton 's machine(Mac Homebrew Apache with PHP 7.3).

### **Screenshots**
Screenshot_2022-02-28_17-22-57
Screenshot_2022-02-28_17-23-27
unknown

### CODE REVIEW

**Comment by SKuipers** [comment]
Hi @thefudgeishot I'm looking forward to checking this out. Could you update the name of the PR to be a bit more specific to your code changes, as this would end up in our commit log for the core once it's merged 😄

**Review by SKuipers — CHANGES_REQUESTED** [review]
Hi @thefudgeishot It's been a busy couple weeks, thanks for your patience as I reviewed this. This looks like a great feature to add into the core and I think it will certainly help people to sync their calendars and timetables 😃 

I've added some notes about isActionAccessible, and a few other areas to change. Shouldn't be major changes, just some tweaks, but please feel free to give a shout with any questions about the comments or changes. Thanks!

**Comment by thefudgeishot** [comment]
Hey @SKuipers glad you like the feature, thanks for the suggestions! I've just finished adding all the new suggestions and I have tested it on my machine (Manjaro GNU/Linux Pacman XAMPP Apache with 7.4.27). Just let me know if you'd like me to change anything else. 
Thanks again!

**Review by SKuipers — APPROVED** [review]
Looking good, thanks for making these changes 👍 I'm going to merge it in and test it out 😃

**Comment by SKuipers** [comment]
Tested out and looking great. I've made a couple post-merge tweaks, to update the composer.lock and to tweak the notification message to add the name of the timetable. I've added this under Significant Changes in the changelog, as I'm sure there will be lots of people happy to see this feature available. Thanks again!

**Pull request merged**
