### PR TITLE
Fix column objects to support multiple buttons

### PR DESCRIPTION
**Pull request by jimbo8098**
Buttons did not identify properly before with IDs, this is now fixed but beware that addButton now requires another value at construction to supply the ID. 

When the column was running getOutput(), the ID was picked but the ID was a string value "NULL" and therefore the ID matches on all buttons inside that column object. This fix uses the ID assigned to the button instead.

### CODE REVIEW

**Comment by SKuipers** [comment]
Thanks for the PR! The Button class is already in use in the codebase so we'd need to be careful changing the constructor signature. Perhaps the $name value be used for both value and name?

The `getName()` and `setName()` methods are part of the InputAttributesTrait so this class should have access to them, it appears the `$this->setName($name)`call was just missed when this class was created. Looks like the two methods you've added may be ovewriting the base class methods and can safely be removed.

Also hate to be a pain 😅  but we're aiming to use PSR-2 as the codestyle for the core. Could you update these changes to use soft tabs (4 spaces). More info here: http://www.php-fig.org/psr/psr-2/#24-indenting  There's often CS-Fixers that can be installed depending on your editor.

Many thanks!!

**Comment by jimbo8098** [comment]
Sure, sounds fine. I'll amend the branch.

RE PSR-2, I'll configure vim next time I'm working on it.

On 24 Oct 2017 9:07 am, "Sandra Kuipers" <notifications@github.com> wrote:

Thanks for the PR! The Button class is already in use in the codebase so
we'd need to be careful changing the constructor signature. Perhaps the
$name value be used for both value and name?

The getName() and setName() methods are part of the InputAttributesTrait so
this class should have access to them, it appears the $this->setName($name)call
was just missed when this class was created. Looks like the two methods
you've added may be ovewriting the base class methods and can safely be
removed.

Also hate to be a pain 😅 but we're aiming to use PSR-2 as the codestyle
for the core. Could you update these changes to use soft tabs (4 spaces).
More info here: http://www.php-fig.org/psr/psr-2/#24-indenting There's
often CS-Fixers that can be installed depending on your editor.

Many thanks!!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GibbonEdu/core/pull/370#issuecomment-338908989>, or mute
the thread

**Comment by jimbo8098** [comment]
Ok I've set vim to use 4 spaces instead of tab chars now. 

I've made a solution to the button class which leaves the constructors for the class alone. When created through FormFactory, the ID is assigned through a 3rd, optional, variable. If no ID is provided, the label is used, as before. If you want to use multiple buttons of the same name, you'll need to use the third variable to set it.

Here's what you can do with the changes:

```
    $frm = Form::create('test',null,'get');

    $frm->addRow()->addButton('hello'); //Create a button with a label and no onclick
    $frm->addRow()->addButton('hello again',null); //Create a button with an imaginary onclick in place of null
    $frm->addRow()->addButton('hello again again',null,'fancyid'); //Create a button with an ID

    //This snippet will make one button since the button objects will use the name 'hello' in the array
    $frmRow = $frm->addRow();
    $frmRow->addButton('hello');
    $frmRow->addButton('hello');

    //This snippet, with buttons embedded in a column will output 3 buttons in said column. You could embed the buttons in a row too since they work in a similar fashion.
    $frmRow2 = $frm->addRow();
    $rowCol = $frmRow2->addColumn();
    $rowCol->addButton('hello',null,'hello1'); //Button with ID 'hello1'
    $rowCol->addButton('hello',null,'hello2'); //Button with ID 'hello2'
    $rowCol->addButton('hello',null,'hello3'); //You get the idea...
    echo $frm->getOutput();
```

**Comment by jimbo8098** [comment]
Bah! No way to change the branch. It's the buttonfix branch. I'll raise a new PR.

**Pull request closed without merging**
