### PR TITLE
School Admin - refactoring, adding null coalesce (WIP)

### PR DESCRIPTION
**Pull request by hmerrettICHK**
**Description**
Refactoring - adding null coalesce (WIP)

**Motivation and Context**

**How Has This Been Tested?**

**Screenshots**

### CODE REVIEW

**Comment by yookoala** [comment]
Test artifacts of the [failed test](https://github.com/GibbonEdu/core/actions/runs/666650761) shows:

* **Parse error**: syntax error, unexpected '$type' (T_VARIABLE) in **/home/runner/work/core/core/modules/School Admin/fileExtensions_manage_editProcess.php** on line **53**.

Please check the syntax of the file. Thanks.

**Comment by hmerrettICHK** [comment]
> Test artifacts of the [failed test](https://github.com/GibbonEdu/core/actions/runs/666650761) shows:
> 
>     * **Parse error**: syntax error, unexpected '$type' (T_VARIABLE) in **/home/runner/work/core/core/modules/School Admin/fileExtensions_manage_editProcess.php** on line **53**.
> 
> 
> Please check the syntax of the file. Thanks.

Found the error - a missing semicolon. Committed a fix now. Thanks!

**Comment by yookoala** [comment]
@hmerrettICHK: Thanks for the swift fix.

Next time if you encounter similar problem, you may click on the red cross of the failed commit, then click "Details" of any of the failed test:
2021-03-19 11-48-43 的螢幕擷圖

Then you will see the detailed test log. You may also download artifacts related to the failed test:
2021-03-19 11-50-57 的螢幕擷圖

The artifact zip file contains a "failed" file that list all the scripts that failed, the test server log (useful to see any PHP warning or error), and usually one or more HTML of the browser view when the test failed. I recovered the above error message with this method.

**Review by SKuipers — APPROVED** [review]
Looking good, I'm going to merge and check it out 👍

**Comment by hmerrettICHK** [comment]
@yookoala Thank you so much for the advice and instructions! I'll keep it in mind for the future

**Pull request merged**
