### PR TITLE
Main page accessibility improvements

### PR DESCRIPTION
**Pull request by leofreitas**
**Description**
- Some adjustments for better accessibility
- I changed the .scss file and build it locally without errors but does not include the css generated in this PR

**Motivation and Context**
System accessibility - full review

**How Has This Been Tested?**
Local

**Screenshots**

Before this PR
before_PR

After
PR_result

### CODE REVIEW

**Comment by SKuipers** [comment]
Hi Leo, thank you for putting this together. With the nature of this year and many different demands on our time, we didn't manage to review this PR for the scope of v21, and we're now into the final testing stages pre-release. I've added it to the top of the v22 todo list. Thanks!

**Comment by yookoala** [comment]
@leofreitas: Some of the files you changed has been updated in the v22.0.00 branch since. Please rebase on the latest v22.0.00 branch.

**Comment by leofreitas** [comment]
Thaks @yookoala ,
The files has been updated.

**Comment by SKuipers** [comment]
Hi Leo, I haven't forgot about this PR! 😅 I've pushed a couple fixes to the resources/build submodule, which accidentally got removed during merge resolution.

I'm _almost_ ready to merge this PR, but I'm hesitant on the point of changing the colours. I realize there are accessibility checkers for contrast ratios, but I'm also aware that these checkers are not infallible [[1]](https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/) [[2]](https://www.bounteous.com/insights/2019/03/22/orange-you-accessible-mini-case-study-color-ratio/), and are a guideline rather than a hard rule. I'm happy to continue the discussion on these, but perhaps we can split out these changes so I can merge in this PR in the meantime.

**Comment by leofreitas** [comment]
Hi Sandra, this question about contrast ratios is very complex. I will close this PR and split it.

**Pull request closed without merging**
