### PR TITLE
Students: Ooification of student report tables

### PR DESCRIPTION
**Pull request by SKuipers**
Four more tables ooified:
- Students by House
- Student Transport
- Roll Group Summary
- Privacy Choices by Student

In working on these tables, the amount of inline copy-pasted html was getting clunky. I've created some simple templates for these sections where we need to include a block of contact details or addresses. This can give us a reusable, consistent format for these types of data.

### CODE REVIEW

**Comment by rossdotparker** [comment]
Post-merge tests looking good so far. One issue is that the formatting of the Excel export from Participants by Activity is formatted oddly, due to the parent contact listing section.

**Comment by rossdotparker** [comment]
Other than that, it looks good : )

**Comment by SKuipers** [comment]
> Post-merge tests looking good so far. One issue is that the formatting of the Excel export from Participants by Activity is formatted oddly, due to the parent contact listing section.

Ahh I see, I bet it's preserving the newlines as well as converting the `<br/>`s. Will push a fix.

**Comment by rossdotparker** [comment]
The pushed fixed looks great. Thanks : )

**Pull request merged**
