### PR TITLE
Typo fixes in POEditor and v18

### PR DESCRIPTION
**Pull request by fvlasie**
fixed in POE

### CODE REVIEW

**Comment by SKuipers** [comment]
Great! Perhaps if you we keep this PR open, you could push typo changes to your `fvlasie:patch-3` branch, and we could merge a group of them at a time? Rather than one PR per typo 😄

**Comment by fvlasie** [comment]
OK

**Comment by rossdotparker** [comment]
Well caught. Keep pushing these changes and we'll merge them in due course. Thanks : )

**Comment by rossdotparker** [comment]
The most recent additions, the number disagreements, make a whole lot of sense!

**Comment by SKuipers** [comment]
Thanks FV! Looks like we've accumulated a decent number of typo fixes. I'm going to merge these in now, feel free to start a new PR if you spot some more.

**Pull request merged**
