### PR TITLE
Planner: refactor breadcrumb translations

### PR DESCRIPTION
**Pull request by yookoala**
**Refactor**
## Description
* use __() to replace previously used strtr() logics.
* New translation string: "`Planner for {classDesc}`".
* New translation string: "`View Lesson Plan for {classDesc}`".

## Motivation and Context
* see #701 and #709.

## How Has This Been Tested?
* Travis

### CODE REVIEW

**Comment by SKuipers** [comment]
Thanks! I wonder if, given the context, the strings `Planner for {classDesc}` and `View Lesson Plan for {classDesc}` may make more sense. In this case, it looks like the context can be either a date or a class name. @rossdotparker thoughts?

**Comment by yookoala** [comment]
Seems a reasonable change to me. Changed ahead first.

Can revert / change to anything.

**Comment by rossdotparker** [comment]
I've merged this, but now seeing the braces on View Lesson Plan:
screenshot 2018-11-22 at 6 47 49 pm

**Comment by rossdotparker** [comment]
Solved it: it was using strtr instead of __

**Comment by rossdotparker** [comment]
OK, I've made a variety of tweaks to this, which can be seen in the commit below:

https://github.com/GibbonEdu/core/commit/2926cbb35364de6061fb477eb331508dc3fada2f

Great team work here to ensure we keep quality control levels up, despite the many changes going on.

**Pull request merged**
