### PR TITLE
System: apply mail template to Password Reset email

### PR DESCRIPTION
**Pull request by SKuipers**
Following up on #817 to add the template to other non-notification emails sent by Gibbon.

### CODE REVIEW

**Comment by crayner** [comment]
So sorry to see this.  Rejected the PR that was working towards this that I
attempted for mail/templates, and then do it anyway.   You confirm my
argument, and will no doubt reject me again. But I will not be silent in
the face of such hypocrisy!
------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Mobile: +61 456 560 018

**Comment by rossdotparker** [comment]
Craig, in the past we worked hard to merge your PRs, all of which contained
valuable ideas.

If you recall, we spent many months going down the architecture road you
suggested, but eventually had to back out due to performance and stability
issues.

Your more recent PRs included some massive changes to /vendor, which
ultimately prevented us from merging them.

There is no effort to silence you, nor to dismiss your work. We welcome
good ideas and good features, and we don't care from where they come, as
long as we can work through any issues that arise.

I'm sure you'll agree that email templates are a pretty common thing, and
so it is hardly like we took an original idea from you. We simply
implemented a useful feature in a different way.

If you don't like what we are doing, please feel free not to participate.
We've not really got the time or inclination to argue or defend ourselves.

Thanks,

Ross

**Comment by crayner** [comment]
Hypocrite!!  Your team leader always dismissed and NEVER DISCUSSED.  Both
of you HYPOCRITES.    I WAS NEVER TOLD THE VENDOR WAS TOO BIG, TOO MANY
CHANGES.  I WAS TOLD OF UNNECESSARY BLOAT, WHICH I WOULD CLEAN AND
RESUBMIT, BUT INVARIABLY THE RESUBMIT WOULD NEVER BE ACTED ON, YOU
HYPOCRITE.  YOU ALWAYS BLAME ME, WHEN IT WAS YOU AND HER.  She does not
know how composer works, and when I tried to teach her, you responded that
my language was unacceptable.  Hypocrite!!   I was trying to teach, by she
is unwilling to learn.  My mistake.  Hypocrite!!
You will only be told you are a hypocrite if you respond, so why bother.
Note,  YOU responded, not her, a true indication of unwillingness to engage
or learn on her part.  Don't worry, I will not do any further work, but
will continue to call out your hypocrisy when I see it.
Hypocrite!!

**Comment by rossdotparker** [comment]
Hi Craig, I'm happy to engage in friendly discussion with you, and you are entitled to your own opinions. I am not going to respond to your accusations one by one, as it will serve little purpose. In summary, however, I answered your message because I a) am the founder of the project b) got to it first and c) did not appreciate the tone. I don't want team members wasting their time replying to messages that I feel are off base and ill-intended, and so I chose to step in. 

I feel that your language has crossed a line here, and certainly you are in breach of our Code of Conduct: https://github.com/GibbonEdu/core/blob/master/.github/CODE_OF_CONDUCT.md.

At this point I am going to have to ask you to remove the last comment you made, and desist from use of such language in future. If you do not, I'll have no choice but to block you from further comments.

Thanks,

Ross

**Pull request merged**
