### PR TITLE
added bigbluebutton

### PR DESCRIPTION
**Pull request by fvlasie**
**Description**

**Motivation and Context**

**How Has This Been Tested?**

**Screenshots**

### CODE REVIEW

**Comment by SKuipers** [comment]
Hi FV, great to see you're up and running with a draft PR of this feature. Give a shout if there's anything we can help with as you get your PR ready for review. 

Cheers,
Sandra

**Comment by fvlasie** [comment]
For some reason git is marking all files as changed even though the content has not been altered on most of them...

**Comment by yookoala** [comment]
1. The file permissions in this PR were changed.
2. Some file had the EOL changed from Unix style to Windows style.

**Comment by yookoala** [comment]
@fvlasie: I've clean up the changes and created a new branch in my repo.

Can you please check if I missed anything here:
https://github.com/GibbonEdu/core/compare/v25.0.00...yookoala:GibbonEduCore:feat/bigbluebutton

**Comment by fvlasie** [comment]
Wow thanks Koala! I will check it. Please save any great editing efforts in case I need to redo the PR...

**Comment by yookoala** [comment]
There is small bug fix I put on a separated commit in that branch. You're welcome to simply include it into your work :-)

**Pull request closed without merging**
