### PR TITLE
Refactor password policy

### PR DESCRIPTION
**Pull request by yookoala**
**Description**
* A new abstraction PasswordPolicy to describe password policies with.
* Have CoreServiceProvider setup to initialize PasswordPolicy from settings gateway.
* Rewrite doesPasswordMatchPolicy and getPasswordPolicy with PasswordPolicy. Also mark both as deprecated.

**Motivation and Context**
* To simplify code related to password policies.
* Pave way to better error message with password policies.

**How Has This Been Tested?**
* Locally.
* CI environment.

### CODE REVIEW

**Review by SKuipers — CHANGES_REQUESTED** [review]
This is looking great, I love to see more code with unit tests 😃 My only suggestion is a very minor semantic change to rename the class `PasswordPolicies` to `PasswordPolicy`, to change it from plural to singular (since a policy already implies multiple rules within itself).

**Comment by yookoala** [comment]
@SKuipers: Renamed.

**Review by SKuipers — APPROVED** [review]
Thanks, looking great! Historically, the `randomPassword` function has generated passwords that did not match the policy. Now that we have this class, when we go to refactor randomPassword, we could add a `PasswordPolicy::generatePassword` method, so we could ensure that the passwords generated satisfied the policy 😄

**Comment by yookoala** [comment]
> Thanks, looking great! Historically, the `randomPassword` function has generated passwords that did not match the policy. Now that we have this class, when we go to refactor randomPassword, we could add a `PasswordPolicy::generatePassword` method, so we could ensure that the passwords generated satisfied the policy smile

Sounds like a cool addition to the class. Will work on that.

**Pull request merged**
