### PR TITLE
System: update code style of likes.php

### PR DESCRIPTION
**Pull request by yookoala**
## Description
Refactor likes.php to separate business logic and display logic.

## Motivation and Context
As part of the effort in addressing #608.

## How Has This Been Tested?
1. Unit test pass.
2. Open test site with the proper address to show likes.php content. It works normally.

### CODE REVIEW

**Comment by SKuipers** [comment]
Hi Koala,

In v16 and v17 we've been introducing a set of Data Table classes to handle the output of html-style tabular data. Much of the system involves displaying tables of things, so this reusable set of classes makes it easier to standardize the display and features of all the tables, and abstracts the table just enough for us to optionally render it in different formats (printable, spreadsheet, possibly even json, xml, etc). 

Here's a gist with some more details on how the tables work (not in the docs yet, it's on my to-do list 😄 ):
https://gist.github.com/SKuipers/e176454a2feb555126c2147865bd0626

The presentation of the data is still separated from the logic: first a Data Set is created, the structure of the Data Table is setup, then the Data Set passed into the Data Table to be rendered.

Would you be interested in updating the Likes table in this PR to use the data table classes rather than plain html? I'm happy to help answer any questions. Thanks!

**Comment by yookoala** [comment]
It takes some reading, but I'll give it a try :-)

**Comment by yookoala** [comment]
Is there any source of dummy data I can use to see the like table? Cause I have nothing to display with in my development environment.

**Comment by SKuipers** [comment]
Perhaps try these, it's the SQL for some fake likes that have accumulated in my own test system:

```
INSERT INTO `gibbonlike` (`gibbonLikeID`, `gibbonSchoolYearID`, `gibbonModuleID`, `contextKeyName`, `contextKeyValue`, `gibbonPersonIDRecipient`, `gibbonPersonIDGiver`, `title`, `comment`, `timestamp`) VALUES
(0000000000000001, 012, 0119, 'gibbonBehaviourID', 1, 0000000000, 0000000001, 'Positive Behaviour', 'Please select...', '2018-02-05 12:56:16'),
(0000000000000002, 023, 0119, 'gibbonBehaviourID', 2, 0000000001, 0000000001, 'Positive Behaviour', 'Collaboration: 123', '2018-05-26 10:37:38'),
(0000000000000003, 023, 0006, 'gibbonAttendanceLogPersonID', 168, 0000000001, 0000002113, 'Attendance - Self Registration', '', '2018-06-11 14:14:09'),
(0000000000000004, 023, 0012, 'gibbonPlannerEntryHomeworkID', 1, 0000000001, 0000002117, 'Crowd Assessment Feedback', 'ICT07.1: Epic Wallpaper 6', '2018-06-11 14:45:02'),
(0000000000000005, 023, 0009, 'gibbonPlannerEntryID', 82851, 0000000001, 0000000001, 'Planner - Learning Feedback', 'FL08.2: fdsaf', '2018-09-09 12:00:24');
```

**Comment by yookoala** [comment]
@SKuipers: Done. Please check.

**Comment by yookoala** [comment]
Looks cleaner than what I did. Nice :-)

**Comment by yookoala** [comment]
Good to know `$guid` is phasing out :-)

**Pull request merged**
