### PR TITLE
Render tables - Support to internationalization

### PR DESCRIPTION
**Pull request by leofreitas**
## Motivation and Context
Add support for internationalization for content columns, for example:
schoolYear_manage.php
gradeScales_manage.php
attendanceSettings.php
fileExtensions_manage.php

## How Has This Been Tested?
Local and Travis

### CODE REVIEW

**Comment by rossdotparker** [comment]
@SKuipers can you foresee any cases where this backfires?

**Comment by SKuipers** [comment]
Hmm, I think there could be, if partial string replacements were applied to user-entered text where it was not intended. I can see where it's needed though for some fields like enums being pulled from the database. The way to handle this could be a translatable flag/method for columns that require the translation wrapper, and update the columns where this is applicable.

**Comment by rossdotparker** [comment]
Do you see that as something for v17 or v18? I'd lean towards the latter at this point I think.

**Comment by SKuipers** [comment]
Hi Leo,

We're back again, and since it's v18 not it's be great to get this issue sorted. I'm thinking we may need to flag a Column in the DataTable as `translatable()`. This way, they're not all translated by default, but the funcionality would be there for the columns that need it (such as Enums coming from the DB). What do you think? Want to try your hand at that change? 😃

**Comment by leofreitas** [comment]
Hi Sandra,
That's great! I'll start working on it.

**Comment by crayner** [comment]
Hi Leonardo,'
   This is only an idea, and you do not have to use it.
   One of the frameworks I use often has a flag on the Select and Radio
Group called translate_choice.  If translate choice is false, then no
translation is done, or if otherwise the prompt is translated.

So

$row->addSelect('gibbonYearGroupID')->fromArray(array('all' => __('All')))->
fromQuery($pdo, $sql)->selectMultiple()->selected($yearGroups);
may look like
$row->addSelect('gibbonYearGroupID')->fromArray(array('all' => __('All')))->
fromQuery($pdo, $sql)->selectMultiple()->translateChoice(true)->selected(
$yearGroups);
The renderer would then be responsible to translate the prompts if the
translate_choice is not false.
------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Mobile: +61 456 560 018

**Comment by leofreitas** [comment]
Hi Crayner,
Thanks for sharing. I think that's a good idea! :wave:

**Comment by leofreitas** [comment]
Continues in #785

**Pull request closed without merging**
