### PR TITLE
Attendance: refactor breadcrumb

### PR DESCRIPTION
**Pull request by yookoala**
**Refactor**
## Description
adapt the new `$page` global for breadcrumb.

## Motivation and Context
See #696

## How Has This Been Tested?
* Locally
* Travis

### CODE REVIEW

**Comment by SKuipers** [comment]
A great start! Looks like a typo in some breadcrumbs, `$page->breadcrumb` should be `$page->breadcrumbs` 

I think we can remove the `// set page breadcrumbs` comments, the line of code is pretty short and self-documenting : )

Thanks!

**Comment by SKuipers** [comment]
Thanks! Can you remove the `// set page breadcrumbs` comments too? Then it looks ready to merge.

**Comment by yookoala** [comment]
Done.

**Comment by rossdotparker** [comment]
Hi @yookoala thanks for making all of these changes. They are merged and I've tested them. Along the way I found and fixed two minor errors, which you can see in the commit below:

https://github.com/GibbonEdu/core/commit/8928f041f2a05e974496feb8c23a5e919c262e73

Would you mind checking to see if you can spot the same kind of errors in the outstanding PRs that you have? That way you can fix them before merging.

The reason that the delete has no breadcrumb is that it is displayed in a modal.

**Comment by yookoala** [comment]
Thanks @rossdotparker, will check my other PRs for that.

**Pull request merged**
