### PR TITLE
V18 PHPOffice/PHPSpreadsheet Integration

### PR DESCRIPTION
**Pull request by crayner**
The current package PHPOffice/PHPExcel is generating a warning stating:
**Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.**

This is the start of work to replace the abandoned package with the recommended replacement.  This PR add the PHPOffice/PHPSpreadsheet package, and creates a wrapper for local use and manage Gibbon settings.  The PR also alters the Student Transport Report to use the new package.  
### References:
https://stackoverflow.com/questions/41117762/what-are-the-main-differences-between-phpexcel-and-phpspreadsheet
https://phpspreadsheet.readthedocs.io/en/develop/topics/migration-from-PHPExcel/
https://www.htmlgoodies.com/beyond/making-the-switch-from-phpexcel-to-phpspreadsheet.html

### Testing:
- The testing included the visual inspection of the before and after spreadsheet output.  I was not able to see any differences.
- codeception passed
- phpunit passed

### Questions/Issues:
Gibbon\Database\Connection deprecated the getResult() method in v16.  I do not understand why this is deprecated and no alternative has been provided by the deprecator, so I am forced to use getResult().  Re-writing the Connection class is outside the scope of this PR.  This may need resolution by the team leaders.  Please let me know how to proceed here?

### Future Targets Scope of Work
This lists the files that currently use PHPOffice\PHPExcel found using a search of \PHPExcel and Gibbon\Excel

>         Gibbon 
>               indexExport.php  (1 usage found)
>                      46 $exp = new Gibbon\Excel();
>              modules\Departments  (1 usage found)
>                  department_course_classExport.php  (1 usage found)
>                      60 $exp = new Gibbon\Excel();
>              modules\Finance  (2 usages found)
>                  expenses_manage_processBulkExportContents.php  (1 usage found)
>                      64 $excel = new Gibbon\Excel('expenses.xlsx');
>                  invoices_manage_processBulkExportContents.php  (1 usage found)
>                      77 $excel = new Gibbon\Excel('invoices.xlsx');
>              modules\Library  (1 usage found)
>                  report_catalogSummaryExportContents.php  (1 usage found)
>                      80 $excel = new Gibbon\Excel('catalogSummary.xlsx');
>              modules\Markbook  (2 usages found)
>                  markbook_viewExportAllContents.php  (1 usage found)
>                      82 $excel = new Gibbon\Excel('markbookAll.xlsx');
>                  markbook_viewExportContents.php  (1 usage found)
>                      76 $excel = new Gibbon\Excel('markbookColumn.xlsx');
>              modules\Students  (1 usage found)
>                  report_transport_studentExportContents.php  (1 usage found)
>                      40 $excel = new Gibbon\Excel('studentTransport.xlsx');  **Now integrated to 
>             modules\System Admin  (4 usages found)
>                 export_run.php  (4 usages found)
>                     59 $excel = new \PHPExcel();
>                     63 'fill' => array('type' => \PHPExcel_Style_Fill::FILL_SOLID, 'color' => array('rgb' => 'eeeeee')),
>                     64 \PHPExcel_
>                     268 $objWriter = \PHPExcel_IOFactory::createWriter($excel, $exportFileType);
>             src\Data  (4 usages found)
>                 Importer.php  (4 usages found)
>                     251 $objReader = \PHPExcel_IOFactory::createReader('Excel2003XML');
>                     254 $objPHPExcel = \PHPExcel_IOFactory::load($filePath);
>                     256 } catch (\PHPExcel_Reader_Exception $e) {
>                     275 $objWriter = \PHPExcel_IOFactory::createWriter($objPHPExcel, 'CSV');
>             src\Gibbon  (4 usages found)
>                 Excel.php  (4 usages found)
>                     21 class Excel extends \PHPExcel
>             src\Tables\Renderer  (9 usages found)
>                 SpreadsheetRenderer.php  (9 usages found)
>                     52 $excel = new \PHPExcel();

### CODE REVIEW

**Comment by crayner** [comment]
So, how should we proceed with this update.  The issue I have is a lack of data with which to test changes.  The PR for Student Transport is available now, and the dummy data is OK for that page.  Still, I am not comfortable submitting inadequately tested code.  I wait for your guidance on this issue.

**Comment by crayner** [comment]
I have taken to opportunity to rename the export files to reflect the names of the class/roll being exported.

**Comment by crayner** [comment]
So, on digging, I found student Transport reports had been breeding, and there was stuff here, there and everywhere.  So consolidated into one.  
CourseClass Export now also a single entity, using RenderTable Class.
Addition and specific notes in the commit comments.

**Comment by crayner** [comment]
Invoice Export changes the render by not setting the borders on every cell.  Was this necessary for some reason other than ascetics?

**Comment by SKuipers** [comment]
Hi Craig,

Looks like you've put a lot of time into this! The PR is getting pretty big. We do try to carefully review code and test it, so the goal of keeping PRs small helps to ensure the overall quality of the codebase. 

Are you able to PR just the composer and vendor additions as a separate change set? Keep this PR open too, and once the vendor changes are merged in we will better be able to review and test these changes.

For now, it would help to hold off on further additions to the PR too, until we've had a chance to review.

Thanks!

**Comment by crayner** [comment]
Not a problem Sandra.  I will do that now as I am offline for the next week+.  I have found and am using the ReportTable class to manage all exports, so eventually the Excel and Spreadsheet Wrapper will not be required at all.  The PHPOffice/PHPSpreadsheet is call directly in the SpreadsheetRender.  Hopefully this remove a lot of duplicated code.  I just pushed the Expense stuff to the PR, so it may have crossed your message.

**Comment by crayner** [comment]
Hi Sandra,
The way that Monolog works you can chain the logs, so a log for mysql is written twice, in mysql and gibbon files.  In our site, this menas adding another Render to the mysql group.  Also, the mysql in the production site could still record everything, but the gibbon file only errors and warning. It all depends on how you define the LoggerHandler.  At the moment this is all hard coded, but it would not take much  to add this to the factory as options to be set in the container.

**Comment by SKuipers** [comment]
Sounds great. Yep np, I'm coming up to Chinese New Year break here and will be offline soon too. Hope to get a chance to review it before then, thanks!

**Comment by SKuipers** [comment]
Hmm, there seems to be a lot of composer-related changes still in this PR 🤔  We've since added the PHPSpreadsheet library, are you able to rebase this changeset so it contains only those changes related to the intended scope? This will help make it possible to review. Thanks!

**Pull request closed without merging**
