### PR TITLE
Replace "/vendor" with automatic installation bundle in release (Travis CI)

### PR DESCRIPTION
**Pull request by yookoala**
Instead of keeping a `/vendor` folder in the repository, we tell Travis CI to build and submit additional bundle for easy installation.

**Description**

1. Add a GitHub asset release script for uploading arbitrary files and attach to GitHub release.
2. Add a "[deploy](https://docs.travis-ci.com/user/deployment/)" section in the .travis.yml to have Travis run `composer install`, build an archive with everything and submit to GitHub as part of a tagged release (see "[Script Deployment](https://docs.travis-ci.com/user/deployment/script/)" for more details).
3. Remove "/vendor" folder from the repository (this change messed with the diff here, but you can checkout my branch and diff the individual commits there).

**Motivation and Context**

The current GibbonEduCore includes the `/vendor` in the repository so that the release "Source code" archives would have all the files and folders needed for installation. This is for the ease of installation to school system admin who are not familiar with composer. However, this is considered an anti-pattern in modern PHP source code management (as discussed before in threads like #462).

To remove the "/vendor" folder while still supporting system admin to install / upgrade their Gibbon, we need a way to release archive files that has the proper "/vendor" folder after it is removed from the source.

Since Gibbon is using Travis CI for continuous testing, the logical approach is to use Travis to build such archive and release it.

This PR add a generic GitHub asset releasing script "cli/github-release.sh" for releasing the "Install Bundle" (the archive file(s) for easy installation). Then add some instructions to Travis so it would build and release the archives at appropriate triggers (i.e. Tag, Environment variables, branch, etc).

**How Has This Been Tested?**

The approach is tested in [my fork of GibbonEduCore](https://github.com/yookoala/GibbonEduCore/) for some times. It works:

* [Travis CI build record](https://travis-ci.org/github/yookoala/GibbonEduCore/jobs/734781546)
* [Result (buildtest3)](https://github.com/yookoala/GibbonEduCore/releases/tag/v21.0.00-buildtest3)

**Screenshots**
2020-10-12 11-55-09 的螢幕擷圖

### CODE REVIEW

**Comment by yookoala** [comment]
If you have your own Gibbon fork and already enabled Travis CI for it, you may test the build process by:
1. Checkout my branch to your own frok
2. Create your own [Personal access token](https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token) at [Settings > Developer settings > Personal access tokens](https://github.com/settings/tokens).
3. Make sure the token has these scopes:
    2020-10-12 12-18-18 的螢幕擷圖
4. In Travis CI, open the setting page for your fork of Gibbon. Define a new environment variable `GITHUB_DEPLOY_TOKEN` with your new GitHub token as value.
5. Tag any commit then push the tag to your fork. For example:
    ```
    git tag v21.0.00-buildtest1
    git push --tag
    ```
6. Open your Travis at `https://travis-ci.org/github/*username*/GibbonEduCore` to monitor the build process.
7. Open `https://travis-ci.org/github/*username*/GibbonEduCore/releases` to see the resulting release(s).

**Comment by SKuipers** [comment]
Hi Koala, thank you for putting this together. With the nature of this year and many different demands on our time, we didn't manage to review this PR for the scope of v21, and we're now into the final testing stages pre-release. I've added it to the top of the v22 todo list. Thanks!

**Comment by yookoala** [comment]
Understood. I guess I might try another version in GitHub Action, in case Travis have further issues supporting open source projects.

**Comment by yookoala** [comment]
Rebase on the latest v21.0.00 branch to fix merge conflict.

**Comment by SKuipers** [comment]
Thanks Koala for all the work setting these up and testing it. I think we'll go with the GitHub Actions version 👍

**Pull request closed without merging**
