### PR TITLE
Display application form in two languages

### PR DESCRIPTION
**Pull request by myii**
### Intro
* First up, apologies for the length, I've tried to be as brief as possible, honest!
* It's understood that this isn't ready to be merged right off the bat - still needs a lot of input and finalisations
* Corresponds to issue #31
* No hard-coding!  But have used a number of relative symlinks to `.mo` files...
* Note: The submit button for changing the translation is to the far left of the selection box - terrible UX on my part, enjoy the irony with respect to 9376359!

#### 49f3614
* This is my first foray into locales, gettext, etc. - so I'd be happy to find out there is a better solution
* However, garnered my understanding of using `dgettext` from:
  * http://www.sitepoint.com/localizing-php-applications-3/
  * http://mel.melaxis.com/devblog/2005/08/06/localizing-php-web-sites-using-gettext/
* What I've gathered (practically) is that `dgettext` will look in the same directory as the current `.mo` being used
* Thus, realised that **relative** symlinks would be the way forward, to minimise disk usage and upkeep (only needs to done once)
  * By relative, I mean to the `i18n/` directory
  * For example: `ar_SA.mo -> ../../ar_SA/LC_MESSAGES/gibbon.mo`
  * This enables the symlinks to be distributed as part of the package and work out of the box
* So for now, set them up for each of the supported languages, in each supported language directory
* Potential issues:
  * Gibbon installs on Windows (does this even happen?) - junctions available, though
  * If moving forward with this method, will need to add symlinks for all other languages

#### e936d96
* This is the wrapper function for `gettext` (i.e. `_()`)
* Also has the form selection input used for testing translations quickly - this is only for faster testing and **is in no way appropriate for production**!  See below...
* Main code issues:
  * `bi()` - closest rendition to `_()` that is somewhat relevant in meaning
  * Function arguments and default values:
    * `$string`: As usually passed to `_()`
    * `$use_bi`: Default to `_()`, have to opt-in to `bi`
    * `$delimeter`: Use `<br \>` by default between original string and translation
    * `$use_styling`: Use CSS styling (i.e. blue text) by default but allow to be switched off where inappropriate (e.g. form input, error messages, etc.)
  * Using `post` instead of `get`, simply because I couldn't figure out how to get the latter working!
  * Form input:
    * Based on code already in Gibbon (realised now that I forgot to comment my changes for this section)
    * Main difference is not showing every language; if the base language is the same, do not display as an option - e.g. no benefit in translating `en_GB` to `en_US`
* Potential issues (translation selection input):
  * If translation is changed after any fields are filled, that data will be lost!
  * Our use case for resolving this (may not be appropriate in general):
    * Since all of our users are required to input in the system default language (English in our case), that language must always be displayed
    * For logged-in users, using system default language => no translation, no option to select
    * For logged-in users, not using system default language => show system default language translation, no option to select
    * Otherwise => display in system default language, with option to select
  * Based on this, we'll probably determine the selection on `index.php` and not have any translation changes on the application form itself

#### 16d23b0
* Vim-based search and replace to convert most lines with `_(...)` to `bi(..., True)`

#### 4fe485e
* Vim-based search and replace (x2) to convert remaining lines with `_(...)` to `bi(..., True)`

#### 5cb2ed9
* Relevant lines changed to use `' | '` separator instead of default `<br \>`

#### 340d0de
* Same again but this time for lines where CSS styling not to be used

#### bc5eb19
* **Even if we don't go forward with this PR**, these lines should be addressed in order for translation to take place
* `_()` not found being used for certain lines - no translation being done for these strings

#### 883aa21
* **Even if we don't go forward with this PR**, these changes should be considered in order for translation to take place
* This particular commit took a fair bit of effort but I've included my solution in the commit log, as a basis for any further work in this area
* Noticed that this particular string was not being translated for any of the other languages
* Saw the the Unicode characters were the issue, so made the relevant changes to get it all working
* Potential issues:
  * Due to my inexperience, there's probably some simpler way to achieve all of this; please use those methods instead and we can overlook this particular commit
  * If sticking to this method, will need to redo this commit for all languages (rerun the commands appropriately)

#### e321a64
* Fixed typo
* Also included for `bi()` but obviously no translations available yet

#### 9376359
* Getting ahead of myself here so ignore this commit if I've overlooked something
* Main rationale is UX: Only being used for `officialName`, inconsistent with all other input boxes
* As for translation: Seem to be unable to use line breaks, which makes longer translations wrap over lines - particularly annoying for RTL languages

#### 6552975
* Translation: For better readability

### Notes
* There's a little(?!) more besides the above but we'll see how we get on with this first...
* Haven't included CSS changes to space things out a little nicer
* Have queries regarding improving all of the "Parent/Guardian" lines, e.g.:
```
<h4><?php print sprintf(bi('Parent/Guardian %1$s Personal Data', True), $i) ?></h4>
```
* ...

### CODE REVIEW

**Comment by rossdotparker** [comment]
myii,

Wow, you put a lot of work into this, it seems, so double extra sorry for
sitting on it for so long.

I have had a look, and whilst I love the idea of having the application
form in two languages, I think the symbolic link solution (whilst very
smart) is too much of a hack for production. The network effect, as more
and more languages are added will make this hard to maintain, and I just
get a feeling it might be something we regret. Can you see another way to
make it work?

Perhaps the application page could have a special language option dropdown
at the top, that sets the language just for that page?

In terms of the commits bc5eb19 and 883aa21, I do want to commit those, but
for now would rather they use _() instead of bi(), untill we resolve the
issues with double translation. Would you mind recommitting the code with
_() instead?

Finally, yes the Official Name is terrible UX, but lots of users used it
wrong, and that was the best way I could think of to get them to do it
right. Suggestions welcome!

Thanks again for the time you have put into Gibbon thus far.

Cheers,

Ross

On Thu, Jul 9, 2015 at 3:33 AM, myii <notifications@github.com> wrote:

> Intro
>
>    - First up, apologies for the length, I've tried to be as brief as
>    possible, honest!
>    - It's understood that this isn't ready to be merged right off the bat
>    - still needs a lot of input and finalisations
>    - Corresponds to issue #31
>    <https://github.com/GibbonEdu/core/issues/31>
>    - No hard-coding! But have used a number of relative symlinks to .mo
>    files...
>    - Note: The submit button for changing the translation is to the far
>    left of the selection box - terrible UX on my part, enjoy the irony with
>    respect to 9376359
>    <https://github.com/GibbonEdu/core/commit/93763592d15f779b3d761a1f0b1660a754051e9c>
>    !
>
> Explaining each commit 49f3614
> <https://github.com/GibbonEdu/core/commit/49f3614efc2659edc571952f2c15eca796570f89>
>
>    - This is my first foray into locales, gettext, etc. - so I'd be happy
>    to find out there is a better solution
>    - However, garnered my understanding of using dgettext from:
>       - http://www.sitepoint.com/localizing-php-applications-3/
>       -
>       http://mel.melaxis.com/devblog/2005/08/06/localizing-php-web-sites-using-gettext/
>    - What I've gathered (practically) is that dgettext will look in the
>    same directory as the current .mo being used
>    - Thus, realised that *relative* symlinks would be the way forward, to
>    minimise disk usage and upkeep (only needs to done once)
>       - By relative, I mean to the i18n/ directory
>       - For example: ar_SA.mo -> ../../ar_SA/LC_MESSAGES/gibbon.mo
>       - This enables the symlinks to be distributed as part of the
>       package and work out of the box
>    - So for now, set them up for each of the supported languages, in each
>    supported language directory
>    - Potential issues:
>       - Gibbon installs on Windows (does this even happen?) - junctions
>       available, though
>       - If moving forward with this method, will need to add symlinks for
>       all other languages
>
> e936d96
> <https://github.com/GibbonEdu/core/commit/e936d9656433b58531905c27bfa8cc65e3f4cbd1>
>
>    - This is the wrapper function for gettext (i.e. _())
>    - Also has the form selection input used for testing translations
>    quickly - this is only for faster testing and *is in no way
>    appropriate for production*! See below...
>    - Main code issues:
>       - bi() - closest rendition to _() that is somewhat relevant in
>       meaning
>       - Function arguments and default values:
>          - $string: As usually passed to _()
>          - $use_bi: Default to _(), have to opt-in to bi
>          - $delimeter: Use <br \> by default between original string and
>          translation
>          - $use_styling: Use CSS styling (i.e. blue text) by default but
>          allow to be switched off where inappropriate (e.g. form input, error
>          messages, etc.)
>       - Using post instead of get, simply because I couldn't figure out
>       how to get the latter working!
>       - Form input:
>          - Based on code already in Gibbon (realised now that I forgot to
>          comment my changes for this section)
>          - Main difference is not showing every language; if the base
>          language is the same, do not display as an option - e.g. no benefit in
>          translating en_GB to en_US
>       - Potential issues (translation selection input):
>       - If translation is changed after any fields are filled, that data
>       will be lost!
>       - Our use case for resolving this (may not be appropriate in
>       general):
>          - Since all of our users are required to input in the system
>          default language (English in our case), that language must always be
>          displayed
>          - For logged-in users, using system default language => no
>          translation, no option to select
>          - For logged-in users, not using system default language => show
>          system default language translation, no option to select
>          - Otherwise => display in system default language, with option
>          to select
>       - Based on this, we'll probably determine the selection on index.php
>       and not have any translation changes on the application form itself
>
> 16d23b0
> <https://github.com/GibbonEdu/core/commit/16d23b0bd49893b2ab9e607a8ce7d5a709096670>
>
>    - Vim-based search and replace to convert most lines with _(...) to bi(...,
>    True)
>
> 4fe485e
> <https://github.com/GibbonEdu/core/commit/4fe485efa5a5fcc5007ec58956a0fca4476d5bdd>
>
>    - Vim-based search and replace (x2) to convert remaining lines with
>    _(...) to bi(..., True)
>
> 5cb2ed9
> <https://github.com/GibbonEdu/core/commit/5cb2ed96104d98789126a4f699f5990148d53832>
>
>    - Relevant lines changed to use ' | ' separator instead of default <br
>    \>
>
> 340d0de
> <https://github.com/GibbonEdu/core/commit/340d0dec690b3314e8b3881c7ea66c0627cb7ff7>
>
>    - Same again but this time for lines where CSS styling not to be used
>
> bc5eb19
> <https://github.com/GibbonEdu/core/commit/bc5eb197d61df4a2deefeebf246a27998470db88>
>
>    - *Even if we don't go forward with this PR*, these lines should be
>    addressed in order for translation to take place
>    - _() not found being used for certain lines - no translation being
>    done for these strings
>
> 883aa21
> <https://github.com/GibbonEdu/core/commit/883aa213680a7f006e517b959e30115e734d066e>
>
>    - *Even if we don't go forward with this PR*, these changes should be
>    considered in order for translation to take place
>    - This particular commit took a fair bit of effort but I've included
>    my solution in the commit log, as a basis for any further work in this area
>    - Noticed that this particular string was not being translated for any
>    of the other languages
>    - Saw the the Unicode characters were the issue, so made the relevant
>    changes to get it all working
>    - Potential issues:
>       - Due to my inexperience, there's probably some simpler way to
>       achieve all of this; please use those methods instead and we can overlook
>       this particular commit
>       - If sticking to this method, will need to redo this commit for all
>       languages (rerun the commands appropriately)
>
> e321a64
> <https://github.com/GibbonEdu/core/commit/e321a648b0567a84245fb770b00d9adf109f1433>
>
>    - Fixed typo
>    - Also included for bi() but obviously no translations available yet
>
> 9376359
> <https://github.com/GibbonEdu/core/commit/93763592d15f779b3d761a1f0b1660a754051e9c>
>
>    - Getting ahead of myself here so ignore this commit if I've
>    overlooked something
>    - Main rationale is UX: Only being used for officialName, inconsistent
>    with all other input boxes
>    - As for translation: Seem to be unable to use line breaks, which
>    makes longer translations wrap over lines - particularly annoying for RTL
>    languages
>
> 6552975
> <https://github.com/GibbonEdu/core/commit/6552975aa74af3878f1335beedeb1a3f83604380>
>
>    - Translation: For better readability
>
> Notes
>
>    - There's a little(?!) more besides the above but we'll see how we get
>    on with this first...
>    - Haven't included CSS changes to space things out a little nicer
>    - Have queries regarding improving all of the "Parent/Guardian" lines,
>    e.g.:
>
> <h4><?php print sprintf(bi('Parent/Guardian %1$s Personal Data', True), $i) ?></h4>
>
>
>    - ...
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/GibbonEdu/core/pull/32
> Commit Summary
>
>    - Create symlinks to all translations within each translation
>    - Create gettext wrapper function & basic form for switching
>    translations
>    - Convert most gettext _() calls to use new wrapper bi() instead
>    - Convert remaining gettext _() calls to use new wrapper bi()
>    - Print translation with separator instead of line break
>    - Print translation with separator instead of line break, no styling
>    - Apply bi() where gettext _() originally missing
>    - Fix msgid texts causing missing translations
>    - Fix spelling error and missing gettext _() call via. bi()
>    - Remove inconsisent use of input title for officialName textboxes
>    - Split first paragraph to allow translation to be easier seen
>
> File Changes
>
>    - *A* i18n/ar_SA/LC_MESSAGES/ar_SA.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-0> (1)
>    - *A* i18n/ar_SA/LC_MESSAGES/en_GB.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-1> (1)
>    - *A* i18n/ar_SA/LC_MESSAGES/en_US.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-2> (1)
>    - *A* i18n/ar_SA/LC_MESSAGES/es_ES.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-3> (1)
>    - *A* i18n/ar_SA/LC_MESSAGES/fr_FR.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-4> (1)
>    - *M* i18n/ar_SA/LC_MESSAGES/gibbon.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-5> (0)
>    - *M* i18n/ar_SA/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-6> (2)
>    - *A* i18n/ar_SA/LC_MESSAGES/it_IT.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-7> (1)
>    - *A* i18n/ar_SA/LC_MESSAGES/zh_HK.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-8> (1)
>    - *A* i18n/en_GB/LC_MESSAGES/ar_SA.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-9> (1)
>    - *A* i18n/en_GB/LC_MESSAGES/en_GB.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-10> (1)
>    - *A* i18n/en_GB/LC_MESSAGES/en_US.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-11> (1)
>    - *A* i18n/en_GB/LC_MESSAGES/es_ES.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-12> (1)
>    - *A* i18n/en_GB/LC_MESSAGES/fr_FR.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-13> (1)
>    - *M* i18n/en_GB/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-14> (2)
>    - *A* i18n/en_GB/LC_MESSAGES/it_IT.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-15> (1)
>    - *A* i18n/en_GB/LC_MESSAGES/zh_HK.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-16> (1)
>    - *A* i18n/en_US/LC_MESSAGES/ar_SA.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-17> (1)
>    - *A* i18n/en_US/LC_MESSAGES/en_GB.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-18> (1)
>    - *A* i18n/en_US/LC_MESSAGES/en_US.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-19> (1)
>    - *A* i18n/en_US/LC_MESSAGES/es_ES.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-20> (1)
>    - *A* i18n/en_US/LC_MESSAGES/fr_FR.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-21> (1)
>    - *M* i18n/en_US/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-22> (2)
>    - *A* i18n/en_US/LC_MESSAGES/it_IT.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-23> (1)
>    - *A* i18n/en_US/LC_MESSAGES/zh_HK.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-24> (1)
>    - *A* i18n/es_ES/LC_MESSAGES/ar_SA.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-25> (1)
>    - *A* i18n/es_ES/LC_MESSAGES/en_GB.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-26> (1)
>    - *A* i18n/es_ES/LC_MESSAGES/en_US.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-27> (1)
>    - *A* i18n/es_ES/LC_MESSAGES/es_ES.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-28> (1)
>    - *A* i18n/es_ES/LC_MESSAGES/fr_FR.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-29> (1)
>    - *M* i18n/es_ES/LC_MESSAGES/gibbon.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-30> (0)
>    - *M* i18n/es_ES/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-31> (2)
>    - *A* i18n/es_ES/LC_MESSAGES/it_IT.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-32> (1)
>    - *A* i18n/es_ES/LC_MESSAGES/zh_HK.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-33> (1)
>    - *A* i18n/fr_FR/LC_MESSAGES/ar_SA.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-34> (1)
>    - *A* i18n/fr_FR/LC_MESSAGES/en_GB.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-35> (1)
>    - *A* i18n/fr_FR/LC_MESSAGES/en_US.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-36> (1)
>    - *A* i18n/fr_FR/LC_MESSAGES/es_ES.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-37> (1)
>    - *A* i18n/fr_FR/LC_MESSAGES/fr_FR.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-38> (1)
>    - *M* i18n/fr_FR/LC_MESSAGES/gibbon.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-39> (0)
>    - *M* i18n/fr_FR/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-40> (2)
>    - *A* i18n/fr_FR/LC_MESSAGES/it_IT.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-41> (1)
>    - *A* i18n/fr_FR/LC_MESSAGES/zh_HK.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-42> (1)
>    - *M* i18n/id_ID/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-43> (2)
>    - *A* i18n/it_IT/LC_MESSAGES/ar_SA.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-44> (1)
>    - *A* i18n/it_IT/LC_MESSAGES/en_GB.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-45> (1)
>    - *A* i18n/it_IT/LC_MESSAGES/en_US.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-46> (1)
>    - *A* i18n/it_IT/LC_MESSAGES/es_ES.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-47> (1)
>    - *A* i18n/it_IT/LC_MESSAGES/fr_FR.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-48> (1)
>    - *M* i18n/it_IT/LC_MESSAGES/gibbon.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-49> (0)
>    - *M* i18n/it_IT/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-50> (2)
>    - *A* i18n/it_IT/LC_MESSAGES/it_IT.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-51> (1)
>    - *A* i18n/it_IT/LC_MESSAGES/zh_HK.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-52> (1)
>    - *M* i18n/pl_PL/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-53> (2)
>    - *M* i18n/pt_PT/LC_MESSAGES/gibbon.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-54> (0)
>    - *M* i18n/pt_PT/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-55> (2)
>    - *M* i18n/sw_KE/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-56> (2)
>    - *M* i18n/zh_CN/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-57> (2)
>    - *A* i18n/zh_HK/LC_MESSAGES/ar_SA.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-58> (1)
>    - *A* i18n/zh_HK/LC_MESSAGES/en_GB.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-59> (1)
>    - *A* i18n/zh_HK/LC_MESSAGES/en_US.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-60> (1)
>    - *A* i18n/zh_HK/LC_MESSAGES/es_ES.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-61> (1)
>    - *A* i18n/zh_HK/LC_MESSAGES/fr_FR.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-62> (1)
>    - *M* i18n/zh_HK/LC_MESSAGES/gibbon.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-63> (0)
>    - *M* i18n/zh_HK/LC_MESSAGES/gibbon.po
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-64> (2)
>    - *A* i18n/zh_HK/LC_MESSAGES/it_IT.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-65> (1)
>    - *A* i18n/zh_HK/LC_MESSAGES/zh_HK.mo
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-66> (1)
>    - *M* modules/Application Form/applicationForm.php
>    <https://github.com/GibbonEdu/core/pull/32/files#diff-67> (637)
>
> Patch Links:
>
>    - https://github.com/GibbonEdu/core/pull/32.patch
>    - https://github.com/GibbonEdu/core/pull/32.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/32>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by myii** [comment]
Apologies for the late response - start of the academic year has been very busy.

I fully appreciate not wanting to use this method.  It was an interesting exercise at least.

I no longer have a workable Gibbon installation to test changes on but I've already managed to "blindly" convert those 2 commits to use standard `gettext` based on the latest dev branch.  Do you still want them?  I started putting them in a PR but I'll just get your feedback first before cluttering.

**Comment by rossdotparker** [comment]
Thanks for following up. I can guess how busy you are, based on how busy I
am ; ) Start of year madness.

If you want to push it, I will take a look when time permits. Thanks!

Ross

On Sat, Sep 19, 2015 at 4:16 PM, myii <notifications@github.com> wrote:

> Apologies for the late response - start of the academic year has been very
> busy.
>
> I fully appreciate not wanting to use this method. It was an interesting
> exercise at least.
>
> I no longer have a workable Gibbon installation to test changes on but
> I've already managed to "blindly" convert those 2 commits to use standard
> gettext based on the latest dev branch. Do you still want them? I started
> putting them in a PR but I'll just get your feedback first before
> cluttering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/32#issuecomment-141635263>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by myii** [comment]
OK, done @ #42 -- hope it helps.

I'm not well-versed with GitHub etiquettes so forgive me if I'm doing the wrong thing by closing this PR!

**Pull request closed without merging**
