### PR TITLE
Consistent sort

### PR DESCRIPTION
**Pull request by st3phan1e**
Fixed consistency for $sort.

### CODE REVIEW

**Comment by rossdotparker** [comment]
This is a good start Steph, but needs to involve other pages too. See if you can work it out, otherwise I can help you.

**Comment by st3phan1e** [comment]
So, I should add this to all the pages in the students module?

**Comment by rossdotparker** [comment]
Steph,

Not all the pages, but all the pages that belong to the student_view*.php
action. Make sense?

Ross

On Mon, Mar 16, 2015 at 2:48 PM, Steph Ng <notifications@github.com> wrote:

> So, I should add this to all the pages in the students module?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/11#issuecomment-81451948>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by st3phan1e** [comment]
Sorry for taking such a long time - it's the last few days of the break and there's a lot to do.
I don't find the $search anywhere else other than student_view and student_view_details. Should I add the $search and $allStudents as well?

**Pull request merged**
