### PR TITLE
System: add Weekly Attendance Summary CLI

### PR DESCRIPTION
**Pull request by SKuipers**
**New Feature**

From feature requests on the development roadmap: https://trello.com/c/LjKqL7th

## Description
The Weekly Attendance Summary is a breakdown of student absences and lates over a one-week span (intended to be sent on or after Fridays). Student absences are listed by weekday, grouped and ordered by Form Group. Hopefully this is a useful format & amount of information, happy to update it with any feedback.

## Motivation and Context
Helps admin and office staff keep track of the overall absences for the school week and follow up as needed.

## How Has This Been Tested?
Tested locally and in production at TIS.

## Screenshot
Example from demo data:
screen shot 2017-10-16 at 10 19 03 am

### CODE REVIEW

**Comment by rossdotparker** [comment]
Sandra, looks great : ) Thanks as always for your hard work here. Wonder if, when self registration is enabled, we can get self registration details in there too. One for the wish list!

**Comment by SKuipers** [comment]
Thanks! Should be do-able. Would it be the number of times in a week the student has not self-registered that you'd be looking to see?

**Comment by SKuipers** [comment]
[Weekly absence report by roll group](https://trello.com/c/LjKqL7th/27-weekly-absence-report-by-roll-group)

**Comment by rossdotparker** [comment]
Yes, I think seeing the number of times in a week the student has not self-registered would be excellent. Thanks : )

**Pull request merged**
