### PR TITLE
V25.0.01

### PR DESCRIPTION
**Pull request by cui-soft**
I integrated [bigbluebutton](https://bigbluebutton.org/) video meeting with planner on gibbon.
Please review and send feedback.
Thank you.

### CODE REVIEW

**Comment by fvlasie** [comment]
Thank you for your help Wenlan!

**Comment by cui-soft** [comment]
How are you, @yookoala ?

May I have a question?

I am integrating rocketchat to send bbb video link before starting planner.
I need to run the script on every minute to check plannner's start time.
I noticed that some scripts in cli directory are running like cron job.
Excuse me but can you let me know how I can configure to run a script as cron job?
Looking forward to your kindly reply.

Thank you.

**Comment by yookoala** [comment]
@cui-softs: I don't think there is a cron system in Gibbon (@SKuipers please correct me). I believe you need to write your own script, then setup cron / scheduler in your server OS.

**Comment by cui-soft** [comment]
@yookoala Thank you for your reply.

I want to see how I can run script in core/cli directory.

**Comment by yookoala** [comment]
@cui-soft: They are simple PHP scripts. If you have PHP properly installed on your server, you can run them by the command:

```
php path/to/the/script.php
```

To schedule a command run periodically on server:
* Linux server: [cron job](https://phoenixnap.com/kb/set-up-cron-job-linux).
* Mac server: cron job can be setup like Linux, or you may use [various GUI](https://superuser.com/questions/44849/user-friendly-way-to-schedule-jobs-in-mac-os-x) to setup the scheduled job.
* Windows server: [Task Scheduler](https://www.windowscentral.com/how-create-automated-task-using-task-scheduler-windows-10)

**Comment by cui-soft** [comment]
Thank you for your kindly reply.

**Comment by SKuipers** [comment]
Hi @cui-soft and @fvlasie, thanks for developing this feature, its looking like it will be beneficial to many schools in the community and we appreciate your contributions to the core. Thanks @yookoala for your replies as well 👍 

I've been reviewing the code and have chatted with Ross about some of the best ways we could implement these types of changes. Integrating with different software and APIs certainly presents interesting opportunities to extend Gibbon's capabilities 😃  In the interest of flexibility and maintainability, our thinking is that these implementations will work best as additional modules for Gibbon, which could be shared on the Extend page of Gibbon, enabling schools to see and choose integrations that interest them. Otherwise, we run the risk of adding many settings and libraries to the core that are not used by the majority of Gibbon installations. A modular approach opens up to a wider possible set of options for schools.

With this in mind, we certainly appreciate that you've delved into the monolith that is the core and found ways to integrate your changes 😅 Luckily, it looks like some of the student profile areas that you're looking to change already have hooks in them, designed for modules to add their own sub-pages to these areas. Other areas don't already have hooks, but I'd be happy to work on developing new hooks for these areas, to open up more integration options for developers. Similarly, the settings and libraries you've added for the core could potentially be added to an additional module. I think much of the code you already have here can be tweaked and transported into a dedicated BigBlueButton module without too much re-writing.

Here are some thoughts on next steps for integrating this:

- Check out the [Starter Module](https://github.com/GibbonEdu/module-gibbonStarterModule) to setup a new module.
- See if you can setup a hook for your Student Profile change. Here's [some documentation](https://docs.gibbonedu.org/developers/getting-started/module-development/#module-hooks) and [a hook example](https://github.com/GibbonEdu/module-freeLearning/blob/main/Free%20Learning/manifest.php#L583).
- Add your gibbonSetting entries to your module's manifest and move the settings fields into a Settings page in the module itself.
- Be sure to create a new script extending BackgroundProcess in your module /src folder to add your runVideoChatRequest method to.
- Scripts in your module /src folder are auto-loaded into the namespace Gibbon\Module\ModuleName.
- I'll work on adding hooks for the Staff Profile and Lesson Planner to v25.
- I'll implement Custom Fields for lesson plans in v25, enabling your module to utilize the includeVideoChat and sendVideoLink fields you need in the add/edit planner pages.

Let me know that you think. Ross and I are both keen to see these kinds of integrations in Gibbon and appreciate your time developing it to this point! Ideally, using a module will give developers such as yourself more control over creating and maintaining their integration in the long run.

For future developments, feel free to give a shout anytime to let us know what you have in mind. We're always happy to discuss and suggest how different improvements may fit best into the core 😄

**Comment by SKuipers** [comment]
Hi @cui-soft, I've added hooks for Staff Profile and Lesson Planner to v25 in [this commit](https://github.com/GibbonEdu/core/commit/36ea9ef389a2fd2d674f3aac6020aaaa3fc8bfab), which should help with integrating your changes.

**Comment by cui-soft** [comment]
Hello @SKuipers, thank you for reviewing and commenting.

Yes, you're right.
Originally, I was trying to implement this feature as module with @fvlasie.
But I could not find the way to hook Staff Profile and Lesson Planner.
Let me try to update my code with module by using your commit.

Thank you.

**Comment by SKuipers** [comment]
Thanks @cui-soft, great to hear. I will work to add the next part, the custom fields for lesson plans, in the next couple days and update you. Give a shout if you have any questions, the documentation may yet be a bit confusing 😅

**Comment by cui-soft** [comment]
How are you, @SKuipers?

Excuse me, but can you give me an instruction how I can run php scripts in core/cli directory?
It seems like cron job but I am not sure how I can setup it.
Looking forward to your kindly reply.

Thank you.

**Comment by SKuipers** [comment]
Hi @cui-sof. The scripts in the cli directory can be run using the server's cron tab, there is no additional software needed, you can schedule them using `crontab -e` at whatever frequency the school prefers. Here's an example of running a cli script via cron on a LAMP server:

`10  00    * * * cd /var/www/gibbon/cli/ ; php userAdmin_statusCheckAndFix.php`

**Comment by cui-soft** [comment]
How are you, @SKuipers ?

I am trying to make a module for BigBlueButton integration.
I have some questions on module development.

1. Extra composer install
I need to install "bigbluebutton/bigbluebutton-api-php" composer package.
But I am not sure where I can insert this part on module.
May I write about this on readme file in module?

2. BigBlueButton setting menu
I had plan to add BigBlueButton setting page on Third Party Settings.
But you asked to move the settings on module setting.
https://prnt.sc/s3Re9ISGSbgr
Are you okay with this or may we hook the third party setting page, too?

3. Custom fields for lesson plans
I am waiting your another commit to add custom fields on planner_add/edit pages.

4. Cron job work on module
BigBlueButton Video Chat should be started 10 minutes early than planner start time.
To check all planner's starting time on every minutes, I made a script in cli directory.
How can I integrate this in module?

Looking forward to your kindly reply.

Thank you.

**Comment by SKuipers** [comment]
Hi @cui-soft, thanks for your great questions and continued development on this module.

1. Extra composer install
    - Modules don't hook into the system-level composer file, and for stable installations we pre-install and bundle the vendor folder, rather than asking users to run composer (we aim to lower the barrier to entry, as many IT people in schools do not have dev experience). 
    - For a module such as yours, I would recommend setting up composer within your module folder, with it's own vendor folder and composer files for dev purposes. 
    - To release the module, a good way to do this would be to commit the vendor folder contents and include them in your module download, then add the `require __DIR__ . '/vendor/autoload.php';` to the scripts in your module as needed, to load your module's autoloader.

3. Yes, it's generally best to keep your module settings within your own module, this way they can be installed with the manifest, version controlled with your module, and updated with the module's CHANGEDB file.

4. Thanks for the nudge, I'll be sure to add this in the next day or so and update you here.

5. Users will need to schedule the cron on their own server, so one way to help would be to add instructions to the top of your settings page giving them the CLI file path and even a sample crontab entry for them to copy into their system crontab.

Cheers,
Sandra

**Comment by SKuipers** [comment]
Hi @cui-soft, we've just merged PR https://github.com/GibbonEdu/core/pull/1653 which adds the custom fields for Lesson Plans. My thinking is that your additional module could write the custom fields it needs into the table when installed (using the Settings section in the manifest, which runs SQL statements). Then, you could use those fields as needed. Give a shout with any questions, thanks!

**Comment by SKuipers** [comment]
I see you've closed this PR, which makes sense if you're now working on an additional module. Please feel free to give a shout if there's anything you need or anything we can help with as you work on that development. Cheers!

**Pull request closed without merging**
