### PR TITLE
add nice Arabic font and fixed some styles for rtl

### PR DESCRIPTION
**Pull request by msaied**
https://github.com/msaied/core

**Description**
add nice Arabic font and fixed some styles for rtl

**Motivation and Context**
The font used by it was not a good appearance

**How Has This Been Tested?**
I hane installed project localy and tested the styles

**Screenshots**
Capture

### CODE REVIEW

**Comment by SKuipers** [comment]
Hi @msaied, the photo looks great! 😃 It appears some of the changes haven't come through in the branch you've PRed. Our current development branch is v18.0.00. Can you re-apply your changes onto this v18 branch, then update the base branch for your PR using the edit button in the far top-right of this page. Thanks!

**Comment by msaied** [comment]
Hi @SKuipers, thanks 😊
I re-applied the changes to v18 branch

**Comment by SKuipers** [comment]
Hmm, I’m not seeing any changes (aside from docs files, which may have carried over from the master branch). If you have a local repository on your computer with changes, be sure to push them to your remote repository. If you’re using the command line, here’s some info that may help: https://help.github.com/en/articles/pushing-to-a-remote  Otherwise if you use a UI it should have a “push” option. Hope this helps!

**Comment by SKuipers** [comment]
Hi @msaied. You screenshot looks great, give a shout if you have any questions getting this PR ready to merge, we're happy to help. Thanks!

**Comment by msaied** [comment]
Hi @SKuipers, I pushed the changes here https://github.com/msaied/core/tree/v18.0.00 , is this right?

**Comment by SKuipers** [comment]
Aha, I can see your changes, but they don't show up in the PR here. On closer inspection it looks the the branches in this PR have accidentally ended up comparing the GibbonEdu/core:master to the GibbonEdu/core:v18.0.00.

Screen Shot 2019-04-21 at 5 21 58 PM

No problem though. It doesn't appear to be something you can change with the Edit button, so it looks like you'd need to submit a new pull request from your own branch. Try using this link to submit a new PR: https://github.com/GibbonEdu/core/compare/v18.0.00...msaied:v18.0.00

**Comment by SKuipers** [comment]
Thanks for re-submitting this PR.

**Pull request closed without merging**
