### PR TITLE
Student View Table Sorting

### PR DESCRIPTION
**Pull request by st3phan1e**
Added options to sort the table in student view.

### CODE REVIEW

**Comment by rossdotparker** [comment]
Steph, I have had a look at this, and the sort option looks good. I wonder though if you can include it in the Search section, and change the title of the section to Filter instead of search. That way the controls are in one place. What do you think? Also, make sure the value is passed to students_view_details.php, and back, in the same way that the search string is, so that options persist when using the back button.

**Comment by rossdotparker** [comment]
Also, it is insecure to just put $sort into the SQL, as someone can inject a value in there. You need to paramaterise, like you can see in lines 227 and 228 in your version.

**Comment by st3phan1e** [comment]
Still working on it... sorry for taking so long, teachers decided to put all tests in one week :/

**Comment by rossdotparker** [comment]
No worries! Take your time, and make sure you put school first....then code
; )

On Fri, Feb 27, 2015 at 3:02 AM, Steph Ng <notifications@github.com> wrote:

> Still working on it... sorry for taking so long, teachers decided to put
> all tests in one week :/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/9#issuecomment-76244381>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by st3phan1e** [comment]
Fixed the first two, but I can't figure out how to paramaterise the $sort.
Also, what does -> and => do? I can't seem to find it on google.

**Comment by rossdotparker** [comment]
Steph,

Good work ; )

Do you understand what paramterising means in this context? Or what sql
injection does? I can explain these if you need. Very important for
security.

Most of Gibbon's PHP is written in an older style known as functional
programming. However, the database connections use a new approach called
object oriented. -> means you are calling a function that belongs to a
particular object (e.g. called the fecth() function on a PDO row object).

=> is used in an array to assign a value to a named index in the array.

Hope this helps ; )

Ross

On Sun, Mar 1, 2015 at 3:52 AM, Steph Ng <notifications@github.com> wrote:

> Fixed the first two, but I can't figure out how to paramaterise the $sort.
> Also, what does -> and => do? I can't seem to find it on google.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/9#issuecomment-76542665>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by st3phan1e** [comment]
I think sql injection is when people attach extra sql commands at the end of $sort? I found a nice answer on [stackoverflow](http://stackoverflow.com/a/60496) that (hopefully) explains how to parameterize.
I'll try it in a day or so. A 3-week break is coming up soon so I'll have lots of time to work on projects :)

**Comment by rossdotparker** [comment]
Correct! If you don't parameterise, or at least sanitise, your inputs, you
can end up with people running code sql commands onto the database, with
the same privilege level as the application (e.g. Gibbon in this case).

Enjoy the break ; )

On Mon, Mar 2, 2015 at 8:01 PM, Steph Ng <notifications@github.com> wrote:

> I think sql injection is when people attach extra sql commands at the end
> of $sort? I found a nice answer on stackoverflow
> <http://stackoverflow.com/a/60496> that (hopefully) explains how to
> parameterize.
> I'll try it in a day or so. A 3-week break is coming up soon so I'll have
> lots of time to work on projects :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/9#issuecomment-76700495>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by st3phan1e** [comment]
I've been trying to debug a problem for an hour. Have no idea why it's not working.
On lines 247-249 of [student_view.php ](https://github.com/st3phan1e/core/blob/c7d01bb69f42e0b235cb1faafc5d5fcafebccf87/modules/Students/student_view.php), I parameterised by doing
```php
if ($sort!="") {
	$data+=array("sort"=>$sort);
	$sortSql="ORDER BY :sort";
}
```
but it didn't sort the results at all. However when I do this:
```php
if ($sort!="") {
 	$sortSql=" ORDER BY ".$sort;
}
```
it works! (but it's not parameterised)
What am I missing?

**Comment by rossdotparker** [comment]
Stephanie, not sure, I would have to play with it. I have never
parameterised an ORDER BY, so perhaps it does not work. Another approach is
to check the user input for all appropriate choices, and if a choice is not
appropriate, then set to a sensible default. If you sanitize in this way,
then you don't need to parameterise.

Do you want to try this, and then push the changes? I am going to put a
string freeze on Gibbon 9.1 early next week, so would like to have it ready
by then.

Thanks,

Ross

On Tue, Mar 10, 2015 at 5:13 PM, Steph Ng <notifications@github.com> wrote:

> I've been trying to debug a problem for an hour. Have no idea why it's not
> working.
> On lines 247-249 of student_view.php
> <https://github.com/st3phan1e/core/blob/c7d01bb69f42e0b235cb1faafc5d5fcafebccf87/modules/Students/student_view.php>,
> I parameterised by doing
>
> if ($sort!="") {    $data+=array("sort"=>$sort);    $sortSql="ORDER BY :sort";}
>
> but it didn't sort the results at all. However when I do this:
>
> if ($sort!="") {    $sortSql=" ORDER BY ".$sort;}
>
> it works! (but it's not parameterised)
> What am I missing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/9#issuecomment-78018186>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by st3phan1e** [comment]
Done, it's fixed!
I added this:
```javascript
if ($sort!="surname, preferredName" && $sort!="preferredName" && $sort!="rollGroup" && $sort!="yearGroup") 
{
    $sort="surname, preferredName";
}

**Comment by rossdotparker** [comment]
An elegant solution! Do you want to push the code to the 9.1 branch, and I
will then merge it with 9.1 and test it.

Good work!

Ross

On Thu, Mar 12, 2015 at 4:14 PM, Steph Ng <notifications@github.com> wrote:

> Done, it's fixed!
> I added this:
>
> if ($sort!="surname, preferredName" && $sort!="preferredName" && $sort!="rollGroup" && $sort!="yearGroup")
> {
>     $sort="surname, preferredName";
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/9#issuecomment-78438867>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by st3phan1e** [comment]
So I should close this pull request and then pull the 9.1 branch, then transfer the code from my branch "student-view" to my forked branch"9.1", then submit another pull request from there?

**Comment by rossdotparker** [comment]
Sounds like it should work!

On Thu, Mar 12, 2015 at 5:20 PM, Steph Ng <notifications@github.com> wrote:

> So I should close this pull request and then pull the 9.1 branch, then
> transfer the code from my branch "student-view" to my forked branch"9.1",
> then submit another pull request from there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/9#issuecomment-78446268>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Pull request closed without merging**
