### PR TITLE
Security Robot IP Check at Login/Google Login

### PR DESCRIPTION
**Pull request by crayner**
## Security Robot IP Check at Login
This feature is design to identify machines by IP address that have attempted more that 3 login (failures) within the last 20 minutes and ignore that IP Address for a maximum of 20 minutes.

The system Admin is able to whilte list IP addresses on the System Admin Setting page (Misc Section) using unique IP, subnet or partial IP addresses in a standard comma separated list. e.g 127.0.0.1, 172.16.0 and 192.168.1.1/24 are all valid. Invalid entries are ignored.

127.0.0.1 matches 127.0.0.1
172.16.0 matches 172.16.0.x
192.168.1.1.24 matches 192.168.1.x (this does a bit wise test, so 192.168.1.1/28 would match 16 machines. (Actually 15, due to match all requests on the network.)

### How was this tested?
Tested Both Locally and on Travis

### CODE REVIEW

**Comment by SKuipers** [comment]
Thanks for putting this together. I notice you've introduced some new Manager classes which interact directly with the database. We've been structuring queries using Gateway classes, as these can be easily instantiated with the DI container, and help separate SQL code out of the page into a more reusable location. I find the tendency with Manager classes is they often end up breaking the goal of single responsibility, and become a catch-all for assorted domain logic.

In this case, there doesn't appear to be a gibbonLog or gibbonSettings gateway yet: you'd be welcome to add them, or I'd be happy to push them to your branch, let me know.

**Comment by crayner** [comment]
I would find problem the same with Gateways,  but it is only a name, so I
will not mind.  The trick here is ONE manager PER entity.  The Gateway
functionality would be the Repository for the entity..., so it already
exist with another different name.  These are defined in the entity dcm.yml
files so that doctrine knows how to handle the fields in a table in a
database.
Looking ahead, The manager (gateway) is a single class injector that has
the entity and the repository imbedded and ready to go.  The manager does
embed a trait of standard methods to shortcut common calls such as find,
findBy, findOneBy, and others.
 Anyway, as you decide..
------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Mobile: +61 456 560 018

**Comment by SKuipers** [comment]
It's great you've seen an area to improve and taken the time to put together a PR. In any open source project, the maintainers review code with an aim to keep the codebase consistent, and will often request changes. It's not a matter of splitting hairs, or what works in other frameworks, but whats best for the current codebase.

Working back & forth on the changes to a PR helps to communicate that you respect the time of the developers managing the project and reviewing the code, rather than dismissing the request with "fix it yourself".

**Comment by crayner** [comment]
Thanks Sandra,
I do not agree that what you are doing is best for the codebase.  My
opinion, but as per usual, it means nothing..   VERY VERY UPSET at this end.

 I find the tendency with Manager classes is they often end up breaking the
goal of single responsibility, and become a catch-all for assorted domain
logic.    This is bull, and I called it by pointing out the same argument
on Gateways. Tell the truth, and you will find I respond more favourably.
The truth:  You like the name Gateway, not Manager.  OK.

So, all I understand is that my help is not appreciated (not great) and
that my time is not to be respected as much as your time.  That I
understand and will take appropriate action at my end.  Thanks for you time.

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Mobile: +61 456 560 018

**Comment by SKuipers** [comment]
Craig, it's unfortunate you see it this way. You submitted a PR to an existing codebase, and as developers our goal is to aim for everything to work with the existing code and remain consistent. In this case, we are already using Gateway classes, so my request was to simply to update your code to align with how the current codebase works.

Yes, there's refactoring underway, and people may have different opinions on which directions to take. If the PR was aimed to reassess the entire naming pattern for the Gateway classes, that would be a different discussion. In this particular case, it's perfectly fair for a maintainer to ask a contributor use the current conventions in place, rather than introducing new ones. In the same way we would ask someone to use spaces instead of tabs, because it's the current chosen style in the codebase.

**Comment by crayner** [comment]
Sandra, if you had stated like this rather than the lame way that you did,
making a FALSE excuse as to why, rather than simply stating that we use the
term gateway, not manager, I may have contributed further.  And now you
continue to defend the indefensible.  Please acknowledge that my argument
is valid; that the name Gateway or Manager are BOTH subject to abuse, not
only Manager as you assume, and I would now be a lot happier, but no, you
still wish to hit me with a sledge hammer, when I have already acknowledged
that you as code maintainer have the right to call it what you wish.

I guess my issue is with you and your language,  which I must not be
understanding correctly.    You stated that Manager is subject to abuse,
and because of this you use Gateway.  Not a valid argument as Gateway like
Manager is just a name and both are subject to abuse.  I would have
expected the following change request:

Change Request:  Could you please make the following changes:
Rename SettingManager to SettingGateway to match current codebase usage.
Rename SecurityManager to SecurityGateway to match current codebase usage.
Move SettingGateway, SecurityGateway to folder src\Blah

If I had seen anything like this I would have done it, but what I did
receive was bull and I did not understand if you required me to do
anything, or you where just complaining.

------------------------------------------
I greet you with the great words,
Grace and Peace

Craig Rayner
craig@craigrayner.com
Mobile: +61 456 560 018

**Comment by SKuipers** [comment]
Craig, your choice in language is getting toxic, so I'm locking this thread. When a person submits a PR, the onus isn't on the project maintainers to merge the incompatible code and fix it themselves. That's exactly what you've suggested with the statement "Rename them if you like, or discard the push." People submit PRs and receive feedback all the time, it's a pretty straight-forward way that open source works, and no one hit anyone with a sledgehammer.

I didn't want to get into splitting hairs, but your argument is not valid either, and the fact that you see the change as simply renaming classes makes it increasingly clear you haven't even looked at that part of the codebase. Gateway classes in Gibbon are a single-responsibility database layer, extended from a base Gateway class, and instantiated through the DI container; they do not contain domain logic. In the Manager classes in this specific PR, there is a mix of both SQL queries and domain logic. With a name like SecurityManager in particular, it's pretty ambiguous and does not relate to a specific database entity. The tendency is to then put anything security related in it: authentication, authorization, ip checking, etc, and eventually the codebase ends up with a big catch-all class that breaks the single responsibility principle.

It's clear you have different ideas of how the database should be handled, but that also wasn't the topic of this PR. It's a transitional codebase, undergoing refactoring, and there's parts in the code that represent "how it's done now" as well as "how it was done previously" and "how it will be done in the future". However, even if something is a work in progress, consistency is still important; it's perfectly fair to ask a contributor use the current conventions that are in place, rather than introducing new conflicting ones.

I chose to use general statements in my initial response rather than specifics because you're a competent developer, and suggesting "take a look at how we've already implemented this" should be pretty straight-forward for an experienced developer, rather than giving you a line-by-line laundry list of changes 🤷‍♀️

**Comment by rossdotparker** [comment]
Hi Sandra & Craig, I am sorry to see that this discussion, which started out technical, has become personal. We've managed to avoid this so far in the history of Gibbon, and our positive culture is something I would like to maintain going forward. No flaming, no unkind words, just positive cooperation.

My opinion is that we would be best served by following to the path that Sandra, as maintainer, has laid out for us. Sandra has, through the investment of a lot of time, the fostering of much thoughtful dialogue and the building of trust, established herself as a a worthy captain of this vessel. As maintainer, it is her job to ensure the consistency of the codebase, and to ensure that a plurality of voices results in a single harmony. And that is the job she is aiming to do.

Craig, I appreciate your input into our project, and as Sandra has acknowledged, you are clearly an experienced developer. We'd love to be able to make use of your expertise, but that might require more compromise than you are willing to make, and I would understand that. I'd hate for your good intentions to end up as ill feeling. Please think about if and how you can stay involved and work with us, and we'll do our best to respect your decision.

I'd like the very running of this project to be a model to the children we all work to educate...

**Pull request closed without merging**
