### PR TITLE
WIP: Code style update

### PR DESCRIPTION
**Pull request by yookoala**
An attempt in addressing #608.

## Description
* Restyle code in `index.php` and `likes.php` to separate business logic from display logic.
* Add documentation to `index.php` variables.
* Also some development helper files (docker-compose.yml and .editorconfig).
* Code are gradually changed between commits. Should be easy to follow step-by-step to see what was changed and why.

## Motivation and Context
To make the code base easier for theming and thus responsive design later.

## How Has This Been Tested?
Browsing development copy of the site with the committing changes.

### CODE REVIEW

**Comment by yookoala** [comment]
All tests are passed. Please review if the direction is right. If so, I'd carry on working on `fullscreen.php`and other script files.

**Comment by yookoala** [comment]
Separated the original code_style branch into 4 different PR: #612, #613, #614.

**Comment by SKuipers** [comment]
Awesome, thanks! Will check these out over the weekend.

**Comment by SKuipers** [comment]
Thanks for splitting these out into separate PRs. I've tested them locally and am still running into errors related to loading js and css files on the page. I'll aim to catch-up with you on Slack and we can figure these out.

JS loading errors:
screen shot 2018-09-09 at 7 50 12 pm

CSS missing:
screen shot 2018-09-09 at 7 56 29 pm

**Comment by yookoala** [comment]
Thanks for testing. I think I'd finish the fullscreen.php first. It that is merged, then I can use similar logics (and helper class/function)  here.

**Pull request merged**
