### PR TITLE
Student View Table Sorting

### PR DESCRIPTION
**Pull request by st3phan1e**

### CODE REVIEW

**Comment by rossdotparker** [comment]
Stephanie,

Good work on this, it seems to work well. Please try not to reformat/re-indent all the code as you work. There is a Gibbon-wide indent style, and I would like to keep it consistent. Thanks!

Ross

**Comment by rossdotparker** [comment]
Steph,

Good work on this, it seems to work perfectly. Next challenge (if you want
it) is how you get the sort to persist when you filter, then view a
student, then come back through the breadcrumb trail, or after saving a new
note.

Ross

On Thu, Mar 12, 2015 at 5:49 PM, Steph Ng <notifications@github.com> wrote:

> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/GibbonEdu/core/pull/10
> Commit Summary
>
>    - Added sort options to students view
>    - Fixed interface strings
>    - Merge branch 'master' of https://github.com/GibbonEdu/core
>    - Added sort options to student_view.php
>    - merge
>    - merge Gibbonv9.1
>    - update
>    - Added sort to the Filter section
>    - Fixed sort value in student_details
>    - parameterised sort (buggy)
>    - fixed sort
>    - Merge branch 'Gibbonv9.1' of https://github.com/GibbonEdu/core into
>    Gibbonv9.1
>
> File Changes
>
>    - *M* modules/Students/student_view.php
>    <https://github.com/GibbonEdu/core/pull/10/files#diff-0> (553)
>
> Patch Links:
>
>    - https://github.com/GibbonEdu/core/pull/10.patch
>    - https://github.com/GibbonEdu/core/pull/10.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/10>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by st3phan1e** [comment]
Sure, I'll fix the indents by the way. Should I use a SESSION variable?

**Comment by rossdotparker** [comment]
Steph,

I have fixed them ; )

I try not to use session variables for window/tab-specific information, as
they get can broken by multiple tabs. Take a look at the existing fields on
that page, and how they use parameter passing in links.

Ross

On Fri, Mar 13, 2015 at 9:39 AM, Steph Ng <notifications@github.com> wrote:

> Sure, I'll fix the indents by the way. Should I use a SESSION variable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/10#issuecomment-78738779>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Pull request merged**
