### PR TITLE
User Admin - refactored all breadcrumbs

### PR DESCRIPTION
**Pull request by leofreitas**
Hi,
I finished this module, and would started the module activies.

### CODE REVIEW

**Comment by rossdotparker** [comment]
Wow, Leo you've been busy! I will leave look at this one tomorrow and aim to merge it in. Thanks : )

**Comment by leofreitas** [comment]
Hi Sandra and Ross,
I'm sorry, I don't know how I cannot saw this? :-)

**Comment by leofreitas** [comment]
Hi Sandra and Ross,
I'm sorry, I don't know how I cannot saw this! :-)

**Comment by SKuipers** [comment]
Thanks! Looks great. I've setup an issue so we can track the refactoring progress: #696

**Comment by yookoala** [comment]
@SKuipers: Does the auto-generated breadcrumb object include the module name and path already? Or do we need to do a manual `->add(__(getModuleName($_GET["q"])), getModuleEntry($_GET["q"], $connection2, $guid))` in the middle (when refactoring the breadcrumb)?

**Comment by SKuipers** [comment]
Yep, it includes the module name & entry point already. [Be sure to check out the instructions](https://gist.github.com/SKuipers/b1dd461f5246f257582072596efe8744) 😃

**Comment by rossdotparker** [comment]
@leofreitas can you let me know when you feel this is ready to be merged, and I will take a look. Thanks!

**Comment by leofreitas** [comment]
@rossdotparker this pullrequest is ready to be merge. thanks!

**Comment by rossdotparker** [comment]
@leofreitas it looks good : ) but, you seem to have deleted uploads/.htaccess. Please can you restore this file, and then I will merge and test. Thanks!

**Comment by SKuipers** [comment]
🤦‍♀️ I missed that! Well spotted.

**Comment by leofreitas** [comment]
Hi @rossdotparker,
I restored the folder uploads. 
@SKuipers, I had removed breadcrumbs on delete action, but the travis show me a lot of fails and then I undid.

**Comment by rossdotparker** [comment]
Hi Leo, thanks for persisting with this! The issue with the delete breadcrumbs is that the refactoring will cause a PHP error, which is worse than a Travis error. If you can remove them again, I'll then merge, and we can fix the tests to keep Travis happy. Sorry to create more work for you, hopefully it won't take long!

**Comment by SKuipers** [comment]
I've updated all the tests to no longer check for breadcrumbs on the delete action. Thanks!

**Pull request merged**
