### PR TITLE
Staff: add the ability to create a New Absence and View Absences

### PR DESCRIPTION
**Pull request by SKuipers**
:boom: The next installment in the thrilling adventures of Staff Absence & Friends, following the cliffhanger from issue #866

**Description**
This PR adds the first actions of the Staff Absence feature: New Absence and View Absences.

- The `AbsenceNotificationProcess `is an example of background processing in action: it handles three sub-processes, all related to sending messages to users.
- The `MessageSender` and Message classes are something I'm 
- The `AbsenceCalendar` class is an example of a data table being used to display in a calendar format, with colour-coded hover-over dates, inspired by the min-calendar in the GitHub profiles, but rotated and a bit larger so it's easier to view.
- The `AbsenceView` and `StaffCard` views are reusable view-composer classes for writing info out to a template. The absence details are displayed in a conversational-style view, making it easier to track the status changes over time and who are involved in the absence & coverage process.
- The `AbsenceView` has a couple references to `CoverageViews`, which I've commented out for now but will need later.

_This ended up pretty big, even though I've tried to break it up as much as possible 😅 The Approve Absences, Manage Absences and reports are in future PRs._

**How Has This Been Tested?**
Tested locally & in production.

**Screenshots**

Submit an absence:
Screen Shot 2019-05-09 at 1 20 35 PM

View absences by person:
Screen Shot 2019-05-09 at 1 13 57 PM

View an absence:
Screen Shot 2019-05-09 at 1 20 04 PM

### CODE REVIEW

**Comment by fvlasie** [comment]
I am not sure I like the idea of staff absence being tracked! :)

**Comment by SKuipers** [comment]
> I am not sure I like the idea of staff absence being tracked! :)

Haha 😆 it may be worth it just for the upcoming part of the feature, to handle all the staff coverage arrangements.

**Comment by rossdotparker** [comment]
This really is thrilling! I'm intrigued by modules/Staff/src/MessageSender.php, and why this is specific to this module, rather than being something that is in /src for use across the system.

**Comment by rossdotparker** [comment]
I've had a good browse of this, and it looks great. I am going to merge and test, but I'll need to come back for further study at some point. Too much for my brain in one go, but it is logical to include it all in a single PR. Until the next installment...

**Comment by SKuipers** [comment]
> This really is thrilling! I'm intrigued by modules/Staff/src/MessageSender.php, and why this is specific to this module, rather than being something that is in /src for use across the system.

Thanks! Good question. I'm using this change-set as a bit of a trial run 😄 I think the MessageSender may be useful in the core for notification sending as well as the Messenger module, but wanted to put it through it's paces here first.

**Pull request merged**
