### PR TITLE
modules/Badges OOification Changes

### PR DESCRIPTION
**Pull request by jimbo8098**
This PR adds OOification requirements for my latest PR in the module-badges repo. It adds a domain for use with the Badges module.

### CODE REVIEW

**Comment by SKuipers** [comment]
I see some interesting changes in here I'm keen to check out 👀 It looks like the whole badges module has tagged along for the ride in this PR. I suspect it may need ignored globally on your system or locally in a `.git/info/exclude` file. Also, as we just mentioned in slack, the gateway for the Badges module can live inside the modules/Badges/src folder if it has a `Gibbon\Module\Badges` namespace. Are you able to update these and push your changes to this PR? Thanks!

**Comment by jimbo8098** [comment]
Thanks for the feedback @SKuipers , I've removed the ignored files from the PR along with the BadgesGateway which has been moved to the module-Badges repo instead (based on our Slack conv).

I also spotted some leftover debug in index.php which I've removed.

**Comment by jimbo8098** [comment]
Right, finally got it! So, to recap:

- Moving to $gibbon->session->* instead of $_SESSION where issues were noted. This is mainly within login.php (since I was trying to fix #886 (unsuccessfully). I just noticed student_view_details was hard coded with that module name while using it as an example.
- QueryCriteria now supports array values. It sanitises the input then adds it to the array.
- PaginatedView has been updated to support the array input change above. Prior this caused errors.

You might question the need for array support in QueryCriteria, it's used in order to allow more flexible data transfer. Without it, I'd have had to string encode my array of students rather than simply sending the array.

This can be used in place right now since there is a check on the value of the object prior. However, I suspect this may have been what @SKuipers was referring to when she mentioned "array criteria"?

**Comment by jimbo8098** [comment]
Thanks for your feedback Sandra!

On the subject of the query criteria supporting an array going into the
criteria. This is because on one of he pages in module/Badges, there is a
multi student search. To maintain it I'd either need to use the base PDO or
make the Query criteria handler for it. I can use PDO if that's preferred?

**Comment by SKuipers** [comment]
Hi Jim. This PR ended up with an interesting mix of changes, which is why it hasn't been merged yet. The `$_SESSION` to `$gibbon->session` updates in login.php on their own look good, yet there's some other SID stuff happening in the changes that I'm not sure is necessary 🤔 

It looks like the QueryCriteria changes may be adding a level of complexity to this object that isn't quite intended. The goal of QueryCriteria is to hold values that are passed to and from the front-end via strings (on URL parameters) and as simple JSON objects (via the PaginatedTable renderer). It's possible that there are other ways to achieve what you're looking for without modifying this functionality, such as imploding your IDs to a csv string, or passing them directly as a parameter to the Gateway method being called (eg: `queryBadgesByStudents($criteria, $gibbonPersonIDList = [])`.

**Comment by jimbo8098** [comment]
I'm actually just going to close this, it's such an old PR and it's all over the place anyway so I don't see it being helpful in the current meta. I suspect the recent overhauls will in time resolve it anyway. I'll keep it in my fork and see if it happens again during my tests.

**Pull request closed without merging**
