### PR TITLE
CI: add php 7.1 and 7.2 for CI test

### PR DESCRIPTION
**Pull request by yookoala**
* To test forward compatibility, added PHP 7.1 and 7.2 to Travis
  test.

## Description
* Add php 7.1 and 7.2 to Travis CI test target.

## Motivation and Context
* To test forward compatibility.

## How Has This Been Tested?
* Tested with Travis.

### CODE REVIEW

**Comment by SKuipers** [comment]
Travis is unhappy with the v17.0.00-dev branch right now 😆 Can you rebase this onto the regular v17.0.00 branch? Thanks!

**Comment by yookoala** [comment]
Seems to work in the temp branch right now...

**Comment by yookoala** [comment]
I think it was included in another PR already. So I'll close it for now.

**Comment by SKuipers** [comment]
Oops, nope I didn't include it in the other PR because it was already here. Re-opening it so we can merge this in.

**Comment by yookoala** [comment]
Cherry-picked and it seems fine this time :-)

**Pull request merged**
