### PR TITLE
Update Planner Edit

### PR DESCRIPTION
**Pull request by Qualitymix**
Updates the Planner module with the option to create and link a new Markbook Column when editing an already existing lesson plan.

**Description**
Added lines to planner_edit and planner_editProcess that allows for the creation and linking of a Markbook Column when submitting a change to an already existing lesson plan.

**Motivation and Context**
This helps when planning lessons ahead of time, and a teacher doesn't know whether or not there will be homework. Now, a lesson can be planned ahead, and edited later with the opportunity to add a linked Markbook Column entry to the system.

**How Has This Been Tested?**
Tested and verified on a personal installation of Gibbon v22.

**Screenshots**
EditLesson_1

### CODE REVIEW

**Comment by SKuipers** [comment]
Looking great, thanks @Qualitymix. We're just doing final preparations for the v23 release, so no new features will be merged, but I'll be happy to merge this into the new v24 branch which will be setup in a few days. Thanks!

**Review by SKuipers — APPROVED** [review]
Thanks Nate, now that v24 is underway I'm happy to merge and test this one out 👍

**Comment by SKuipers** [comment]
Oops, I didn't notice it was still attached to the v23 branch, I've reverted that commit and moved it over to the v24 branch here: https://github.com/GibbonEdu/core/commit/c96b2f3533ecd3020841f65c3c6fdec78401f662

**Comment by SKuipers** [comment]
Tests out perfectly, thanks @Qualitymix

**Comment by Qualitymix** [comment]
Great!  I did notice something that is an issue though.  But it's related to another issue that I've been meaning to bring up.  When clicking Submit on a lesson plan, IF the Summary text field is empty, the system will attempt to fill this in with the content from the Lesson Content box.  
If it does this, then, when transitioning to the new markbook edit, it will attempt to bring the content from the Summary field over with it as the description for the new markbook item.  This causes a crash because the Markbook's description text field does not accept as much text as the Summary text field is trying to send it.

**Pull request merged**
