### PR TITLE
Add Saudi Riyal to list of selectable currencies

### PR DESCRIPTION
**Pull request by myii**
Currently evaluating Gibbon for a school in Saudi Arabia; rather delicious that I saw it a few days back (v9.X) but when I came around to downloading it, v10 with the Arabic translation had come out the day before: شكرا!!

Bit of a shame that Saudi Riyal wasn't available but simple enough to add in - that's if I've got it right!  It's worked so far during installation and initial testing but do let me know if I'm missing something important...

I've sneaked in a little typo-correction (x2) along the way.

### CODE REVIEW

**Comment by rossdotparker** [comment]
@myii thanks for contributing this code, which I accidentally merged into the Core. It should have gone into the v11.0.00 dev branch, so I had to revert the merge. I am now testing the changes, which I have copied over to v11.0.00 branch, and will commit shortly.

**Comment by rossdotparker** [comment]
@myii OK, it is in v11 now. https://github.com/GibbonEdu/core/tree/v11.0.00

**Comment by myii** [comment]
Feel bad that it's caused you hassle.  Would it have been more considerate on my part to have made the PR against the v11.0.00 branch in the first place?  In the (unlikely) event that I have another PR to offer?

**Comment by rossdotparker** [comment]
No problem at all, appreciate the help regardless.r

On Sun, Jun 28, 2015 at 10:38 PM, myii <notifications@github.com> wrote:

> Feel bad that it's caused you hassle. Would it have been more considerate
> on my part to have made the PR against the v11.0.00 branch in the first
> place? In the (unlikely) event that I have another PR to offer?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/28#issuecomment-116287025>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by myii** [comment]
@rossdotparker Well I'm back again, after promising to leave you alone!  This isn't directly related to this PR but some quick issues hopefully (the more important ones are points 3 and 4):

1. You may have noticed another message from me about one of your pages having an SSL error?  OK, if you look at the link for **Multilingual, Internationalisation & Localisation** on https://gibbonedu.org/support/administrators/, you will see it is pointing to https://www.gibbonedu.org/... rather than https://gibbonedu.org/... thus, the SSL error

1. I've also seen other little bits here and there on your site (can't recall of the top of my head right now) - is it also Git managed so that you can accept PRs?

1. I've been working with the Arabic translation but that's led me to find some inconsistencies between the code in `applicationForm.php` and the `msgid` values used in the `gibbon.po` files (yes, plural - I've also been fiddling with `en_GB` as well) - shall I put them together in a PR or is there some other process for these sorts of issues?

1. Also following on from my post about locales, I've just found that I had to install the `en_GB` locale on my computer to get that locale working with Gibbon - even though that's the default locale I used for my Ubuntu installation!  It seems that Ubuntu primarily uses `{locale}.utf8` rather than just `{locale}`, if you get my drift.  You may find that this becomes a recurrent theme that users have when working with locales.  Now I don't have much experience with locales but would there be any mileage in providing the `.utf8` versions of the locales as part of Gibbon?  Or maybe even as the default (OK, I'm pushing it here).  At least, perhaps some suggestions on the **Multilingual, Internationalisation & Localisation** page, giving some basic guidance/examples of how it can be resolved.  For my setup, I simply had to do the following to get both `ar_SA` and `en_GB` working:
```
$ sudo locale-gen ar_SA
$ sudo locale-gen en_GB
$ sudo service apache2 restart
```

**Comment by myii** [comment]
@rossdotparker Came across another instance of www.gibbonedu.org in the code itself so did a quick `rgrep` to reveal all of the following broken links:

```
index.php:                                                     <?php print _("Created under the") ?> <a target='_blank' href="http://www.gnu.org/licenses/gpl.html">GNU GPL</a> at <a target='_blank' href='http://www.ichk.edu.hk'>ICHK</a> | <a target='_blank' href='https://www.gibbonedu.org/contribute/'><?php print _("Credits") ; ?></a><br/>

modules/Planner/units_embed.php:                                               print "<p>Smart blocks are <a target='_parent' href='http://www.gibbonedu.org'>Gibbon's</a> unique method for organising the content within a unit. Each block represents an element of a lesson, perhaps an activity, a discussion or even an outcome. Here you can simply view the blocks, but if your school runs Gibbon you can use the blocks to create lessons plans, and use drag and drop to quickly move content between lessons.</p>" ;

modules/Planner/units_embed.php:                                               print "<p>This unit was built with, and is powered by, <a target='_parent' href='http://www.gibbonedu.org'>Gibbon</a> (the open, flexible and free school platform) at " . $_SESSION[$guid]["organisationName"] . "</p>" ;

modules/Planner/units_embed.php:                                               print "<p>This unit was built with, and is powered by, <a target='_parent' href='http://www.gibbonedu.org'>Gibbon</a> (the open, flexible and free school platform) at <a target='_parent' href='" . $_SESSION[$guid]["webLink"] . "'>" . $_SESSION[$guid]["organisationName"] . "</a></p>" ;

modules/System Admin/module_manage_update.php:                                 print "<li>" . sprintf(_('Check %1$s for a newer version of this module.'), "<a target='_blank' href='http://www.gibbonedu.org'>gibbonedu.org</a>") . "</li>" ;
```

Shall I put together a PR for you or will you handle it?

**Comment by rossdotparker** [comment]
myii,

Thanks for all this input. I have just returned from holiday, and will try
and look at this in the coming days. Sorry for the slow response! Usually
we aim for 24 hour turn around on such things, but holidays got in the way.

Cheers,

Ross

On Wed, Jul 1, 2015 at 1:19 PM, myii <notifications@github.com> wrote:

> @rossdotparker <https://github.com/rossdotparker> Well I'm back again,
> after promising to leave you alone! This isn't directly related to this PR
> but some quick issues hopefully (the more important ones are points 3 and
> 4):
>
>    1.
>
>    You may have noticed another message from me about one of your pages
>    having an SSL error? OK, if you look at the link for *Multilingual,
>    Internationalisation & Localisation* on
>    https://gibbonedu.org/support/administrators/, you will see it is
>    pointing to https://www.gibbonedu.org/... rather than
>    https://gibbonedu.org/... thus, the SSL error
>    2.
>
>    I've also seen other little bits here and there on your site (can't
>    recall of the top of my head right now) - is it also Git managed so that
>    you can accept PRs?
>    3.
>
>    I've been working with the Arabic translation but that's led me to
>    find some inconsistencies between the code in applicationForm.php and
>    the msgid values used in the gibbon.po files (yes, plural - I've also
>    been fiddling with en_GB as well) - shall I put them together in a PR
>    or is there some other process for these sorts of issues?
>    4.
>
>    Also following on from my post about locales, I've just found that I
>    had to install the en_GB locale on my computer to get that locale
>    working with Gibbon - even though that's the default locale I used for my
>    Ubuntu installation! It seems that Ubuntu primarily uses {locale}.utf8
>    rather than just {locale}, if you get my drift. You may find that this
>    becomes a recurrent theme that users have when working with locales. Now I
>    don't have much experience with locales but would there be any mileage in
>    providing the .utf8 versions of the locales as part of Gibbon? Or
>    maybe even as the default (OK, I'm pushing it here). At least, perhaps some
>    suggestions on the *Multilingual, Internationalisation & Localisation*
>    page, giving some basic guidance/examples of how it can be resolved. For my
>    setup, I simply had to do the following to get both ar_SA and en_GB
>    working:
>
> $ sudo locale-gen ar_SA
> $ sudo locale-gen en_GB
> $ sudo service apache2 restart
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/28#issuecomment-117438190>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by rossdotparker** [comment]
myii,

Thanks for all this information. Some replies below.

   1. Fixed. This is a pretty empty page, unfortunately.
   2. The site is not Git managed, but bug reports can be sent to
   support@gibbonedu.org and I will look into them.
   3. These fixes would be great as a push request, thanks.
   4. This one is interesting. When Gibbon went multilingual, I followed
   guides online, which from memory, recommended the non-UTF8 version of the
   locale, for whatever reason. I have added to the multilingual page on the
   website, to give some guidance re: locales:
   https://gibbonedu.org/support/administrators/multilingual-internationalisation-localisation/

Thanks for your input ; )

Ross



On Wed, Jul 1, 2015 at 1:19 PM, myii <notifications@github.com> wrote:

> @rossdotparker <https://github.com/rossdotparker> Well I'm back again,
> after promising to leave you alone! This isn't directly related to this PR
> but some quick issues hopefully (the more important ones are points 3 and
> 4):
>
>    1.
>
>    You may have noticed another message from me about one of your pages
>    having an SSL error? OK, if you look at the link for *Multilingual,
>    Internationalisation & Localisation* on
>    https://gibbonedu.org/support/administrators/, you will see it is
>    pointing to https://www.gibbonedu.org/... rather than
>    https://gibbonedu.org/... thus, the SSL error
>    2.
>
>    I've also seen other little bits here and there on your site (can't
>    recall of the top of my head right now) - is it also Git managed so that
>    you can accept PRs?
>    3.
>
>    I've been working with the Arabic translation but that's led me to
>    find some inconsistencies between the code in applicationForm.php and
>    the msgid values used in the gibbon.po files (yes, plural - I've also
>    been fiddling with en_GB as well) - shall I put them together in a PR
>    or is there some other process for these sorts of issues?
>    4.
>
>    Also following on from my post about locales, I've just found that I
>    had to install the en_GB locale on my computer to get that locale
>    working with Gibbon - even though that's the default locale I used for my
>    Ubuntu installation! It seems that Ubuntu primarily uses {locale}.utf8
>    rather than just {locale}, if you get my drift. You may find that this
>    becomes a recurrent theme that users have when working with locales. Now I
>    don't have much experience with locales but would there be any mileage in
>    providing the .utf8 versions of the locales as part of Gibbon? Or
>    maybe even as the default (OK, I'm pushing it here). At least, perhaps some
>    suggestions on the *Multilingual, Internationalisation & Localisation*
>    page, giving some basic guidance/examples of how it can be resolved. For my
>    setup, I simply had to do the following to get both ar_SA and en_GB
>    working:
>
> $ sudo locale-gen ar_SA
> $ sudo locale-gen en_GB
> $ sudo service apache2 restart
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/28#issuecomment-117438190>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Comment by rossdotparker** [comment]
myii,

Thanks for the heads-up here. I have taken care of these, and they will
appear fixed in v11. I think they stem from the change from HTTP to HTTP as
default for the site.

Regards,

Ross

On Wed, Jul 1, 2015 at 7:22 PM, myii <notifications@github.com> wrote:

> @rossdotparker <https://github.com/rossdotparker> Came across another
> instance of www.gibbonedu.org in the code itself so did a quick rgrep to
> reveal all of the following broken links:
>
> index.php:                                                     <?php print _("Created under the") ?> <a target='_blank' href="http://www.gnu.org/licenses/gpl.html">GNU GPL</a> at <a target='_blank' href='http://www.ichk.edu.hk'>ICHK</a> | <a target='_blank' href='https://www.gibbonedu.org/contribute/'><?php print _("Credits") ; ?></a><br/>
>
> modules/Planner/units_embed.php:                                               print "<p>Smart blocks are <a target='_parent' href='http://www.gibbonedu.org'>Gibbon's</a> unique method for organising the content within a unit. Each block represents an element of a lesson, perhaps an activity, a discussion or even an outcome. Here you can simply view the blocks, but if your school runs Gibbon you can use the blocks to create lessons plans, and use drag and drop to quickly move content between lessons.</p>" ;
>
> modules/Planner/units_embed.php:                                               print "<p>This unit was built with, and is powered by, <a target='_parent' href='http://www.gibbonedu.org'>Gibbon</a> (the open, flexible and free school platform) at " . $_SESSION[$guid]["organisationName"] . "</p>" ;
>
> modules/Planner/units_embed.php:                                               print "<p>This unit was built with, and is powered by, <a target='_parent' href='http://www.gibbonedu.org'>Gibbon</a> (the open, flexible and free school platform) at <a target='_parent' href='" . $_SESSION[$guid]["webLink"] . "'>" . $_SESSION[$guid]["organisationName"] . "</a></p>" ;
>
> modules/System Admin/module_manage_update.php:                                 print "<li>" . sprintf(_('Check %1$s for a newer version of this module.'), "<a target='_blank' href='http://www.gibbonedu.org'>gibbonedu.org</a>") . "</li>" ;
>
> Shall I put together a PR for you or will you handle it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GibbonEdu/core/pull/28#issuecomment-117616616>.
>



-- 
*Husband, father, son, brother, friend, coder, teacher & coordinator of
ICT.*
Blog .  http://rossparker.org
Tweets . @rossdotparker <https://twitter.com/rossdotparker>
Opensource .  http://gibbonedu.org
--

**Pull request merged**
