### PR TITLE
New "today" highlight

### PR DESCRIPTION
**Pull request by fvlasie**
Also see next pull request with updates to main.css

### CODE REVIEW

**Comment by SKuipers** [comment]
Hi @fvlasie!

Now that you've mastered setting up separate branches, it may be worth noting that it's okay (and preferable) to put all your related changes together in one branch 😄 This helps make it easier to read & review all the parts of the change on one PR. For example, a PR called "Add Today highlight to timetable" could contain all the file changes for that idea, and then if you had a separate idea or change in a different area of Gibbon then you would create a new branch for it.

Adding commits to the same branch will update an existing PR. In this case, it may help to merge your patch-8 and patch-9 branches into this patch-7 branch, which will combine the changes on one place.

Thanks!

**Comment by fvlasie** [comment]
Sandra, thank you for the tip! I hope I handled that correctly.

**Comment by rossdotparker** [comment]
Hi FV, I think it would be better to avoid the extra div, and just add the class direct to the th tag. In addition, I'd be tempted, for now, just to use this class to set the colour, and leave everything else inline, as this will all need a more complete review in due course. Want to have a play with it?

**Comment by fvlasie** [comment]
Alright! I will see if the highlight can be applied without new elements.

**Comment by fvlasie** [comment]
I think everything is in order this time!

**Comment by rossdotparker** [comment]
This is a big improvement. I've found a way to make it a little more concise, which I've implemented and committed. I noticed that you'd also highlighted the <td> for Timetable by Facility, but not the <th>, so that's also included in the same commit:

https://github.com/GibbonEdu/core/commit/bf165d7ab64a143e54df0e30178b361b1f0c9656

You've made a huge step in contributing to the project, and have already made the system better. Thanks for your time : )

**Comment by fvlasie** [comment]
My pleasure Ross!

**Pull request merged**
