### PR TITLE
v22.0.01

### PR DESCRIPTION
**Pull request by SKuipers**
Since v22 was a pretty big release with a number of structural changes, we've discovered some bugs which have been fixed in v23, but would be good to have available for v22 users. Along with this, we've made a security fix for Messenger which prevents javascript injection in messages, which could be an issue if untrusted users have access to the message wall in a school. These changes were enough to warrant a v22.0.01 patch release.

To PR and review this release, I've created the new v22.0.01 branch in the core which is currently in line with v22.0.00, and have PR the changes from my fork.

See the changelog below for the list of fixes:

Security
        Messenger: fixed sanitization of text when creating new messages

    Bug Fixes
        System: fixed lesson plan content in demo data
        System: fixed checks for existing fields in database migrations
        System: fixed cookie consent message to not redirect to the dashboard
        System: fixed parent dashboard hooks missing access to session object
        Data Updater: fixed data updates with only file uploads in personal documents auto-accepting
        Data Updater: fixed personal documents date bug
        Data Updater: fixed personal documents to only use nationality list for passport and ID documents
        Data Updater: fixed submit button on data updates with no changes
        Departments: fixed Left student role appearing in class list export
        Individual Needs: fixed some IN columns not visible on small screens
        Reports: fixed Left students showing up in the Archive by Student list
        Reports: fixed missing data in CustomFields template data source
        Reports: fixed error with empty milestones when creating a Reporting Cycle
        Reports: fixed issue where re-sending a report will break existing report download links
        Reports: fixed file uploads not working in Template Builder
        Students: fixed ID card background image alignment
        System Admin: fixed importing custom fields failing when existing fields value is null
        System Admin: fixed importing custom fields that have spaces around the values
        User Admin: fixed missing document enum data in migrated personal documents

    Deprecations:
        System: replaced tinymceStyleStripTags function with Validation::sanitizeRichText

### CODE REVIEW

**Comment by rossdotparker** [comment]
This looks good to merge. But I do have two questions before you release:

1.  How come lib/session-timeout/* is removed? This was not in the changelog
2. Do the edited migrations need to be run again?

I'll merge and test now.

**Comment by rossdotparker** [comment]
The install test went well, and the demo data is working. The cookie consent redirect drops URL parameters, which makes it hit and miss in places. I've not had a chance to test each of the fixes in turn, but I know @SKuipers you mentioned you'd do this.

Looking like a great time for this release, with a lot of little annoyances patched.

**Comment by SKuipers** [comment]
Thanks, I've pushed a tweak to v22.0.01 and v23.0.00 to include URL params in the cookie redirect link. https://github.com/GibbonEdu/core/commit/537e8581e033f6ba4c277f5d409aa3298708d355 

I thought I had included the lib/session-timeout in the changelog, I've added it here: https://github.com/GibbonEdu/core/commit/aa63ae01132e36776593e3fe079d3338598cb82f  Its not the whole library, just the package lock file that I've removed, since we're not actively compiling new versions of session-timeout ourselves, it didn't need to be in the core.

The edited migrations shouldn't need to be run again, and there are measures in place to make sure they don't run twice. I've included a line in the changedb to account for fixes to the entries that had already been migrated, such as: https://github.com/GibbonEdu/core/blob/v22.0.01/CHANGEDB.php#L1007

**Comment by rossdotparker** [comment]
Sounds like you've got it all under control Sandra. Thanks for following up : )

**Pull request merged**
