### PR TITLE
OOification: Return Process

### PR DESCRIPTION
**Pull request by raynichc**
**Description**
OOification of Return Processing. This PR deprecates the old returnProcess method and implements a new ReturnMessage class which is handled by Page to process and render return messages. ReturnMessage has methods to set the edit link for a page and add custom returns for processing. For backwards compatibility, the returnProcess method calls the new ReturnMessage methods to set the relevant details.

**How Has This Been Tested?**
Locally on several modules with untouched returnProcess methods and pages altered to use new system.

### CODE REVIEW

**Comment by SKuipers** [comment]
Looking good, nice to see another function removed from functions.php, and the oo approach is nice and clear. 

I notice a switch in logic from `!$session->has('address')` to `$session->has('address')`. I think the former code was in there to handle the dashboards and welcome pages, whereas the returnProcess has been handled individually on pages in the past. I'd like to ideally remove all of the return code from pages, and I think your ooified code can help with this, if we get rid of the `$session->has('address')` check logic entirely. Then, we'll need to do a mass find-replace to delete the existing returnProcess calls, and only add in the `$page->return->addReturns` and `$page->return->setEditLink` calls as needed for those cases. 

It looks like, if I merge the PR currently, we'll see duplicate return messages on all the non-dashboard pages. We may need to get some parallel PRs ready to remove the returnProcess function calls from the codebase, so we can apply these changes at the same time 🤔

**Comment by raynichc** [comment]
Hi Sandra, thanks for having a look. Though I am a little confused by what you mean. As part of the PR, I've disabled the returnProcess method, so instead of printing out a return message it sets the appropriate data using the new methods and rendering is handled by the new system. So there should be no duplicates, right?
I'll also remove the address logic.

**Review by SKuipers — APPROVED** [review]
Aha, thanks for clarifying, I miss-read how the old function was being handled. Looks great! Going to merge and test 👍

**Comment by SKuipers** [comment]
I've used some regex searches to remove/replace the existing returnProcess calls. You can see the commits [here](https://github.com/GibbonEdu/core/commit/c7b24d9d4983a1610f3b4837d47fc645601b69d5) and [here](https://github.com/GibbonEdu/core/commit/86730c8a273c072263fc0845a7ae2bfe0623fb94).

**Comment by raynichc** [comment]
Brilliant, thanks Sandra!

**Pull request merged**
