### PR TITLE
System: deprecate randomPassword

### PR DESCRIPTION
**Pull request by yookoala**
**Description**
* Add a new PasswordPolicy::generate method to generate a random password that's conforming to the rules defined for the instance.
* Rewrite all randomPassword usages with PasswordPolicy::generate().

**Motivation and Context**
* Fix issue when randomly generated password doesn't meet site password policy settings.
* Deprecate usage of randomPassword.

**How Has This Been Tested?**
* Locally.
* CI environment.

### CODE REVIEW

**Review by SKuipers — APPROVED** [review]
Interesting, I didn't realize how many places in the codebase were using randomPassword to generate random strings, rather than the password itself 🤔 I guess in the future this may be better handled by a function that creates strings for the purpose of being uuids. 

I appreciate the time you've put into this, and don't want to leave the PR lingering, so will approve it and test it out, and continue to think on how to deal with uuids vs passwords 🤔

**Comment by yookoala** [comment]
@SKuipers: Just found an issue with phpstan and pushed 1 more commit. Please check and approve this again. Thanks.

**Comment by SKuipers** [comment]
> @SKuipers: Just found an issue with phpstan and pushed 1 more commit. Please check and approve this again. Thanks.

Excellent, love that static analysis 😁 Thanks for catching this!

**Review by SKuipers — APPROVED** [review]

**Comment by SKuipers** [comment]
🎉 PR number 1700 🎉

**Pull request merged**
